### ISSUE TITLE
Support file renames

### ISSUE THREAD

**Issue by scottdorman** [madskristensen/WebCompiler#1]
This may be out of scope for this extension, but what would be really nice is if it could detect file renames and automatically update import statements (or the equivalent include type statement) with the new name.

For example, I have a main.less which looks like:

```
@import "file`.less";
@import "file1.less";
@import "file2.less";
```

If I rename `file1.less` to `buttons.less`, it would be great if the extension could detect that and automatically update the `@import "file1.less"` line to `@import "buttons.less"`.

**Comment by madskristensen** [comment]
That should be a VS thing to rename import references. Renaming `inputFile` in `compilerconfig.json` is problematic because the `outputFile` might also have to be changed. If this is an issue with renaming import references only, then it's already on our backlog at the VS web team and this should be closed

**Comment by scottdorman** [comment]
Yes, I was looking at it only from the standpoint of renaming an import reference. I hadn't thought about the rename affecting the `inputFile` or `outputFile` in `compilerconfig.json`, although (now that you mentioned it), that would be nice as well. This is probably a bit too simplistic of a view, but my thought would be that if I change the input file from `file1.less` (in a folder named less) to `buttons.less`, then the `inputFile` should change from 'less\file1.less` to `less\buttons.less` and the `outputFile` should change from `css\file1.css` to `css\buttons.css` (assuming I'm placing my compiled output in a folder name css). That way, the only thing that's changing is the actual file name itself. I guess another approach would be to detect the rename and pop the save dialog to get the new name for the css file, just like you do when clicking on the "compile" menu option for the first time on a new file.

**Comment by madskristensen** [comment]
I like the idea of just updating the `inputFile` with the new file name

**Comment by scottdorman** [comment]
That would work, but then file names would be out of sync and might cause some confusion. I'm editing a file named `buttons.less` but it's compiling to a files named `file1.css` and `file1.min.css`.

**Comment by madskristensen** [comment]
I'm thinking that the side-effects of renaming `inputFile` and `outputFile` automatically might cause more harm than good. Should we close this for now?

**Comment by scottdorman** [comment]
I'm ok with closing this form now. You're right, automatic renames for both `inputFile` and `outputFile` might create more issues.
