### ISSUE TITLE
Compiling Checks out project file

### ISSUE THREAD

**Issue by ironsides24** [madskristensen/WebCompiler#101]
My source files are stored in TFS and anytime that I compile the LESS files it is automatically checking out the project file. When I compare the file it is exactly the same and no changes have been made. This causes some confusion when you go to check in your changes and the project file is checked out but there wasn't a change made.

**Comment by madskristensen** [comment]
Good point. I'll make sure not to update the output file if nothing changed

**Comment by madskristensen** [comment]
Can you please help verify the fix by installing the latest CI build from here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by ironsides24** [comment]
Still checking out the proj file and now it doesn't update the css files properly. To give you more info I have 1 less file that imports about 15 less files. I am then compiling the 1 less file into 1 css file. The css file does not show the changes from one of the other 15 less files.

**Comment by madskristensen** [comment]
Oops. I made the mistake of checking the timestamp of the referenced file instead of the compiled output. That would then break in case you changed imported files from LESS. Build 1.3.160 should have that fixed. It's ready for testing in a few minutes here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by madskristensen** [comment]
It's ready now for testing

**Comment by madskristensen** [comment]
It will still check out the project file, but not any if the unchanged output files. I'll make a separate fix for the project file
