### ISSUE TITLE
Add documentation of all config options available

### ISSUE THREAD

**Issue by miksh7** [madskristensen/WebCompiler#102]
Please document the all options available in compilerconfig.json & compilerconfig.json.default

In my project compilerconfig.json was created with just two options 
[
  {
    "outputFile": "Content/css/less/base.css",
    "inputFile": "Content/css/less/base.less"
  }
]

**Comment by madskristensen** [comment]
Intellisense in that file provides all available options. Why is documentation needed?

**Comment by miksh7** [comment]
Thanks for a hint, I see it now. Perhaps, mention that in the readme in section compilerconfig.json
Btw, fix typo in this section "conmpilation"
