### ISSUE TITLE
Feature Request: Bless-style CSS File Splitting

### ISSUE THREAD

**Issue by Jared314** [madskristensen/WebCompiler#103]
Bless (http://blesscss.com) splits CSS files based on the IE6-9 limit of 4095 CSS query selectors per file.

While _everyone_ would be glad to be rid of those older versions of IE, including Microsoft, the people who use Visual Studio, for work, are at a higher likelihood of needing to maintain support, in environments that might be hostile to the Node,js-based Bless solution.

**Comment by madskristensen** [comment]
Why not create separate bundles instead? This seems like a feature that used to be handy but less so now and in the future
