### ISSUE TITLE
Wrong relative Urls in LESS escaped url()

### ISSUE THREAD

**Issue by miksh7** [madskristensen/WebCompiler#104]
Consider the following test case:

compilerconfig.json
  {
    "outputFile": "Content/CSS/Test.css",
    "inputFile": "Content/CSS/LESS/Test.less",
    "options": {
      "relativeUrls": true,
      "rootPath": "/"
    }
   }

TEST.LESS
.img-bg(@imagename) {
    background-image:url('../../images/@{imagename}');
}
.img-bg-escaped(@imagename) {
    background-image:~"url('../../images/@{imagename}')";
}

#d-directurl { background-image:url(../../images/noisy_grid.png);}
#d-mixin { .img-bg("noisy_grid.png") }
#d-mixin-escaped { .img-bg-escaped("noisy_grid.png") }

TEST.CSS
#d-directurl {
  background-image: url(../images/noisy_grid.png);
}
#d-mixin {
  background-image: url('../images/noisy_grid.png');
}
#d-mixin-escaped {
  background-image: url('../../images/noisy_grid.png');
}

The last path is incorrect. Note that it was calculated correctly in WE 2013 (at least before VS2015 Update 5).

**Comment by madskristensen** [comment]
Please help verify the fix in the latest CI build here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/
