### ISSUE TITLE
Source maps are placed in-line in .css

### ISSUE THREAD

**Issue by casperno** [madskristensen/WebCompiler#105]
Instead of creating a style.css.map, a base64 encoded version of the map file is placed in the source map link of the css. 

This means the css get a lot bigger than it should be. 

Is there an option that I don't know about?

Using 
sourcemap: true

**Comment by madskristensen** [comment]
There is no option to produce .map files. Aren't you using the .min.css file in production, so does it matter?

**Comment by casperno** [comment]
Hm, sorry. You're right, that makes it a non-issue.
