### ISSUE TITLE
"Re-compile all files…" doesn't do all files

### ISSUE THREAD

**Issue by casperno** [madskristensen/WebCompiler#106]
Hi, 

Thanks for making "Re-compile all files…"  go through all compilerConfig.json's  in project. But it behaves oddly.

Example compilerConfig.json in sub-folder:

        [
          {
            "outputFile": "main_source_sans.css",
            "inputFile": "main_source_sans.scss",
            "minify": {
              "enabled": true
            },
            "sourceMap": false
          },
          {
            "outputFile": "main_roboto.css",
            "inputFile": "main_roboto.scss",
            "minify": {
              "enabled": true
            },
            "sourceMap": false
          },
          {
            "outputFile": "main_source_serif.css",
            "inputFile": "main_source_serif.scss",
            "minify": {
              "enabled": true
            },
            "sourceMap": false
          }
        ]

When doing "Re-compile all files…", only the main_roboto.scss is compiled. 

If I context click the compilerConfig.json and select compile, it works as expected

**Comment by madskristensen** [comment]
Are you sure that it isn't because the output file didn't change? As a new feature the Web Compiler doesn't write the output file to disk if the content of the existing output file is the same. You can check it by deleting all the output files and then run `Re-compile`

**Comment by casperno** [comment]
Hi,

I've did the test again, now deleting all derivative .css first. I was wrong in that only one file was compiled, it turns out that no files were compiled. 

The top level compilerConfig.json is now empty, don't know if that would have an effect.

The scss files I'm trying to compile are two levels down from root.

**Comment by madskristensen** [comment]
I can't repro this. It works fine for me in an MVC app. Are you using the latest CI build from here? http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by casperno** [comment]
weird. 

I'm using version 1.4.170, updated via VS. 

But I not using it from a MVC app, but an old skool .net aspx app. Can that be the difference?

**Comment by madskristensen** [comment]
No, the difference is that you aren't using the latest nightly build that has the feature. Get it here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by madskristensen** [comment]
I just released version 1.5 with this feature to the official Visual Studio Gallery
