### ISSUE TITLE
Wrong paths generated to source map file and sources in sass compiler

### ISSUE THREAD

**Issue by realmerx** [madskristensen/WebCompiler#108]
Thank you for the excellent extension.

With following configuration:

Folder structure:
```
Project\sass\test.scss
Project\sass\test.css
```
compilerconfig.json:

```
[
 {
    "outputFile": "sass/test.css",
    "inputFile": "sass/test.scss",
    "sourceMap": true
  }
]
```

resulting test.css has following sourcemap (decoded from base64 data uri):

```
{
	"version": 3,
	"file": "../test.css",
	"sources": [
		"../test.scss"
	],
	"sourcesContent": [],
	"mappings": "AAAA,IAAI,CAAC;EACF,MAAM,EAAE,eAAgB,GADrB",
	"names": []
}
```

but should be

```
{
	"version": 3,
	"file": "../sass/test.css",
	"sources": [
		"../sass/test.scss"
	],
	"sourcesContent": [],
	"mappings": "AAAA,IAAI,CAAC;EACF,MAAM,EAAE,eAAgB,GADrB",
	"names": []
}
```

(../sass directory prefix is missing on "file" and "sources")

This causes problems in chrome dev tools for example - if you click on scss file on dom explorer, scss file does not open because of incorrect path.

I traced it back to the fact that node-sass resolves paths (I think this explains it better: https://github.com/sass/libsass/issues/908#issuecomment-76452477).

Quick fix that seems to work is to change WorkingDirectory of ProcessStartInfo to Project - currently it is resolved from file being compiled:

When replacing
line 86 on SassCompiler.cs:

```
WorkingDirectory = info.Directory.FullName,
```
with

```
WorkingDirectory = new FileInfo(config.FileName).DirectoryName
```

things seem to work and source map "file" and "sources" paths are generated correctly

**Comment by djanosik** [comment]
@realmerx @madskristensen I think something has changed in libsass and this fix is no longer necessary. Generated paths in source map are relative to configuration file, but they should be relative to input file. The path does not begin with "../" anymore.

**Comment by djanosik** [comment]
@realmerx @madskristensen I think this fix is no longer necessary. Paths are now relative to config file, but they should be relative to input file (like in LESS compiler). Ale there is some issue with paths being changed by autoprefixer.
