### ISSUE TITLE
Compile less files with data-uri breaks

### ISSUE THREAD

**Issue by gpfreak** [madskristensen/WebCompiler#110]
The complie faild with module mime not found when compiling with the newest version.
And the node module mime does not exists in the node_modules folder of WebCompiler in temp folder.

**Comment by madskristensen** [comment]
Can you please add repro steps so I can reproduce the issue?

**Comment by gpfreak** [comment]
We have updated the WebCompiler addin to 1.5.191 and the package to 1.3.165.
We have data-uri in the less files. 
When we say compile, we get the error that the mime module does not exists.

**Comment by madskristensen** [comment]
Please update to nuget package to match at least the version of the extension

**Comment by gpfreak** [comment]
Okay we have now package version 1.5.211, but the problem exists already.

**Comment by madskristensen** [comment]
I cannot reproduce this issue. It works fine for dataURIs of a png file for me. Can you share the LESS code that causes the issue?

**Comment by madskristensen** [comment]
@gpfreak ?

**Comment by gpfreak** [comment]
At us it looks like:
  background-image: data-uri('@{colorpicker-path}img/saturation.png');
