### ISSUE TITLE
Add support for specifying ieCompat in LESS files

### ISSUE THREAD

**Issue by ChrisGrohHS** [madskristensen/WebCompiler#111]
Provide an option to specify the --no-ie-compat setting for data-uri in LESS. This allows embedding data-uris  larger than 32KB which is only necessary for IE8.

**Comment by madskristensen** [comment]
Should it just be the default setting instead of being configurable?

**Comment by ChrisGrohHS** [comment]
Having IE8 compat by default can save you from a gotcha. On the other hand, most sites that list support for data-uri do mention the 32KB limit, projects that support IE8 will only get rarer and rarer, and it shouldn't be that hard to fix even if you don't notice until later in testing.
