### ISSUE TITLE
WebCompiler error 0: 'node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by scott-xu** [madskristensen/WebCompiler#112]
It seems that WebCompiler requires nodejs since some version. However if someone does not install nodejs, it will throw this exception.

**Comment by scott-xu** [comment]
Just noticed that nodejs is put in the temp folder.
https://github.com/madskristensen/WebCompiler/blob/b4b6a581629311e6ac98c3f1207b08874ac6906d/src/WebCompiler/Compile/CompilerService.cs#L15
However files under temp folder might be deleted unexpectedly.

**Comment by madskristensen** [comment]
By design as specified in the PR
