### ISSUE TITLE
Control MSBuild order

### ISSUE THREAD

**Issue by john-jay** [madskristensen/WebCompiler#115]
My build definition is in Visual Studio Online, and my project includes the OctoPack package for deployment. When I queue a build OctoPack runs first, so everything is deployed before my css files are compiled. How can I make WebCompile run first?

**Comment by madskristensen** [comment]
Did you update the nuget package to version 1.5.xxx? That should take care of it

**Comment by john-jay** [comment]
In my packages.config it was:
  <package id="BuildWebCompiler" version="1.5.191" targetFramework="net45" />

I updated it using NuGet to 1.5.197, but that makes it worse:          WebCompiler: Begin compiling compilerconfig.json
         	Compiled Content/styles.css
src\projects\packages\BuildWebCompiler.1.5.197\build\BuildWebCompiler.targets(14,9): Error : Object reference not set to an instance of an object.
     2>D:\_work\4ef56524\EBS-Epiq11\src\projects\packages\BuildWebCompiler.1.5.197\build\BuildWebCompiler.targets(14,9): error : Object reference not set to an instance of an object. [D:\_work\4ef56524\EBS-Epiq11\src\projects\Epiq.EBS.Portal\Epiq.EBS.Portal.csproj]

**Comment by madskristensen** [comment]
What type of project are you using? MVC 5, WebForms, or...?

**Comment by john-jay** [comment]
This is an MVC 5 project. In packages.config it has <package
id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />.


On Fri, Oct 2, 2015 at 3:08 PM, Mads Kristensen <notifications@github.com>
wrote:

> What type of project are you using? MVC 5, WebForms, or...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madskristensen/WebCompiler/issues/115#issuecomment-145142572>
> .
>



-- 
John Holliday, Jr.   -   2213 W 120th St, Leawood, KS 66209  -  816.210.2184

**Comment by madskristensen** [comment]
Can you share the compilerconfig.json and compilerconfig.json.defaults please?

**Comment by john-jay** [comment]
compilerconfig.json
[
  {
    "outputFile": "Content/styles.css",
    "inputFile": "Assets/styles/scss/styles.scss"
  }
]

compilerconfig.json.defaults
{
  "compilers": {
    "less": {
      "autoPrefix": "",
      "ieCompat": true,
      "strictMath": false,
      "strictUnits": false,
      "relativeUrls": true,
      "rootPath": ""
    },
    "sass": {
      "indentType": "space",
      "indentWidth": 2,
      "outputStyle": "nested",
      "Precision": 5,
      "relativeUrls": true
    },
    "coffeescript": {
      "bare": false,
      "runtimeMode": "node"
    }
  }
}

**Comment by madskristensen** [comment]
Hmm, that's what mine look like to. After upgrading to the latest NuGet package, do you see more details in the error message?

**Comment by madskristensen** [comment]
Ok, I can repro now. Fix is coming. thanks for helping out

**Comment by john-jay** [comment]
Sounds good.

**Comment by madskristensen** [comment]
NuGet package version 1.5.215 has the fix

**Comment by john-jay** [comment]
This builds OK in Visual Studio, but it still fails on my build server. 2 problems: 1. OctoPack runs before WebCompiler. 2. WebCompiler has an error.

![image](https://cloud.githubusercontent.com/assets/1194195/10259232/9570987c-692b-11e5-9bdd-fd596941749b.png)

**Comment by madskristensen** [comment]
Did you update the nuget package?

**Comment by john-jay** [comment]
Yes. You can see "215" in the image i attached above.

On Fri, Oct 2, 2015 at 5:34 PM, Mads Kristensen <notifications@github.com>
wrote:

> Did you update the nuget package?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madskristensen/WebCompiler/issues/115#issuecomment-145171824>
> .
>



-- 
John Holliday, Jr.   -   2213 W 120th St, Leawood, KS 66209  -  816.210.2184

**Comment by madskristensen** [comment]
Sorry about that. Now it should be fixed. Version 1.5.216 is building right now and should be ready in a few minutes

**Comment by john-jay** [comment]
That fixed the WebCompiler error. Thanks!

**Comment by john-jay** [comment]
I worked around the OctoPack problem by creating a second Visual Studio build task, and only including the OctoPact build variables in the second one.
