### ISSUE TITLE
Build breaks after nuget package installed

### ISSUE THREAD

**Issue by brunis** [madskristensen/WebCompiler#116]
Hi,

Just installed and can't build any more, i'm getting:
<solution-root>\packages\BuildWebCompiler.1.5.211\build\BuildWebCompiler.targets(14,9): error : Object reference not set to an instance of an object.

dependency issue?

The vs addon works as intended by itself

**Comment by brunis** [comment]
Downgrading to 1.5.203 didn't help, but downgrading to 1.4.197 fixed the problem.

**Comment by madskristensen** [comment]
This is odd. I just ran the nuget package 1.5.211 and it worked fine

**Comment by madskristensen** [comment]
Can you please try to upgrade the NuGet package to 1.5.213 or newer? It includes the .pdb file so the error message should be more clear

**Comment by madskristensen** [comment]
Btw, what type of project do you see this error in? MVC, WebForms, or...?

**Comment by madskristensen** [comment]
NuGet package version 1.5.215 has the fix

**Comment by brunis** [comment]
Sorry, i wasn't online over the weekend, glad you found the issue.
