### ISSUE TITLE
Output autoprefix browser list 

### ISSUE THREAD

**Issue by miksh7** [madskristensen/WebCompiler#119]
When autopefixer is used for compiling less files it would be very helpful if WebCompiler outputs the list of browsers used as described https://github.com/postcss/autoprefixer#debug

**Comment by madskristensen** [comment]
The autoprefixer in this extension is being run through the _less-plugin-autoprefix_ module and it doesn't have that capability unfortunately. When this extension is moved over to run on a node server instead of CLI then it may be possible.
