### ISSUE TITLE
re-compiling is always on and always way too timeconsuming

### ISSUE THREAD

**Issue by brunis** [madskristensen/WebCompiler#121]
Can you stop recompiling unless files change or somehow speed it up? You could use Tasks.Parrallel foreach to start a compile for each core in the system.

**Comment by madskristensen** [comment]
What scenario are you referring to? When you save a file that you haven't changed?

**Comment by brunis** [comment]
Hi,

I'm referring to building my solution. The Build Target is obviously 
always in the project, so the project always executes it:

No matter how many times i choose build solution without changes, this 
will happen:

> ------ Build started: Project: Innomate.Web.Base, Configuration: Debug 
> Any CPU ------
>   Restoring NuGet packages...
>   To prevent NuGet from downloading packages during build, open the 
> Visual Studio Options dialog, click on the Package Manager node and 
> uncheck 'Allow NuGet to download missing packages'.
>   All packages listed in packages.config are already installed.
>   Innomate.Web.Base -> 
> C:\PackageBuilder\Solutions\clean-trunk\INNOMATESolution\Innomate.Web.Base\bin\Innomate.Web.Base.dll
>
>   WebCompiler: Begin compiling compilerconfig.json
>       Compiled Content/DropDownListMenu.css
>       Minified Content/DropDownListMenu.min.css
>       Compiled Content/network-manager.css
>       Minified Content/network-manager.min.css
>       Compiled Content/passwordStrength.css
>       Minified Content/passwordStrength.min.css
>       Compiled Content/print.css
>       Minified Content/print.min.css
>       Compiled Content/Shared.css
>       Minified Content/Shared.min.css
>       Compiled Content/SharedMixins.css
>       Compiled Content/Site.css
>       Minified Content/Site.min.css
>       Compiled Content/TopMenu.css
>       Minified Content/TopMenu.min.css
>   WebCompiler: Done compiling compilerconfig.json
> ========== Build: 1 succeeded, 0 failed, 65 up-to-date, 0 skipped 
> ==========

regards,
Dennis
