### ISSUE TITLE
After on save less compilation urls for fonts are prefixed with less in output css file

### ISSUE THREAD

**Issue by mixanj** [madskristensen/WebCompiler#122]
This is major bug making our site unusable.
Version 1.4.170 worked correctly.
Since version 1.5 this problem appears after on save less compilation.
The compilation on build doesn't seem to have the same issue.

Test example:
fonts.less
@font-face {
	font-family: 'abc';
	src:url('fonts/abc.eot?jp61zb');
}

Expected output in app.css
@font-face {
  font-family: 'abc';
  src: url('fonts/abc.eot?jp61zb');
}

Actual output in app.css after "on save" less compilation
@font-face {
  font-family: 'abc';
  src: url('less/fonts/abc.eot?jp61zb');
}

"less/" shouldn,t be in the path.
Just to mention, none of our font files having less in their actual path at all.

Reinstalling old version and disabling automated updates fixed the problem for now.

**Comment by madskristensen** [comment]
The `fonts.less` file references a file (abc.eot) inside a folder called `fonts`. I assume the folder structure is `/less/fonts/abc.eot` is that correct? Then you compile into `app.css` which is located in what folder?

**Comment by mixanj** [comment]
As I mentioned above, there in NO "less" folder in the whole absolute path to any font file.
Our folder structure:
Content/fonts/<font-files>
Content/less/<less-files>
Content/app.css

**Comment by madskristensen** [comment]
Got it. This is due to a bug in the earlier versions of this extension where it didn't adjust relative paths while compiling LESS files. The issue is that your .less file references a non-existing `abc.eot` file (the folder `fonts' doesn't exist inside the 'less' folder). Instead you must now do the right thing which is to specify the actual path to the `abc.eot` file - so change the reference from `fonts/abc.eot` to `../fonts/abc.eot` and it will work

**Comment by mixanj** [comment]
Interesting that it works correctly with compile on build but incorrectly with compile on save. How is that happening?

**Comment by madskristensen** [comment]
Two very different mechanisms

**Comment by madskristensen** [comment]
It's because you need to update the NuGet package (BuildWebCompiler) to the latest version. MSBuild uses the NuGet package to do the compilation and VS uses the latest bits in the extension when you save a file

**Comment by mixanj** [comment]
Sweet! I just tested it and it works well. Thanks for the help and very quick response!

**Comment by madskristensen** [comment]
You're welcome :)
