### ISSUE TITLE
LESS file not compiling on save

### ISSUE THREAD

**Issue by sitefinitysteve** [madskristensen/WebCompiler#123]
Here's my less file
https://jsbin.com/fipaji/edit?css

On save, nothing happens...the only way I can get this to compile is to right-click the less and force a recompile...?

Any idea, are there logs somewhere?

**Comment by madskristensen** [comment]
Errors will be printed to the output window if there are any.

I can compile your file on save without problems at all. It may be because I updated the LESS compiler in the latest CI build. Can you please install it and verify that it has fixed the issue? 

Download it here: http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by EdwinJow** [comment]
I had the same issue with release version 1.6.  I downloaded the nightly and it fixed the issue.

**Comment by sitefinitysteve** [comment]
Thx, I'll mark as closed guys

**Comment by sitefinitysteve** [comment]
Still not working actually, here's a video:
http://screencast.com/t/D4IIwMCl

Modifying an import item, so if the .css or .min.css change VS should honk at me that the files have changed (when I have them open in a tab); doesn't happen.  If I trigger it manually in the solution explorer all works fine.

**Comment by madskristensen** [comment]
Have you tried the latest CI build? http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

A thing to notice is that when you save a .less file it will compile all .less files listed in compilerconfig.json unless it is itself listed there. In other words, if you compile your .less file but it is also imported into other .less files, those other .less files aren't compiled with it

**Comment by sitefinitysteve** [comment]
Seems to compile now with the latest, thx

I checked, the config just lists the master, none of the imported ones
