### ISSUE TITLE
Changes made on a less file used by other less files should trigger a recompile

### ISSUE THREAD

**Issue by EtienneT** [madskristensen/WebCompiler#125]
Here is a scenario that was working in Web Essentials 2013:

shared.less has some common css imported by a lot of other less files.

theme1.less import shared.less.  Saving shared.less should trigger a recompile of all less files that import it.

Thanks,

**Comment by madskristensen** [comment]
This should work just fine. Do you have the latest version (1.6) of Web Compiler?

**Comment by wazp** [comment]
I have noticed that this stops working every once in a while. Reopening the file seem to make Web Compiler again act on save. Unfortunately I have not been able to figure out where it goes wrong.

**Comment by EtienneT** [comment]
Web Compiler updated with your most recent release from October 9th and it seems to be working now.  Thanks!

One thing that would be pretty convenient would be to have some kind of indication of the % of progress of the generation process when we save a file that impact a lot of other files.  For example we have a less file that 37+ other less files are dependent uppon (client specific themes).  Would be nice to know when the generation process is finished before commiting the newly generated files.

Thanks!
