### ISSUE TITLE
Support the "silent" option for LESS compiler

### ISSUE THREAD

**Issue by mark-gu** [madskristensen/WebCompiler#127]
It would be great if you could add support for the "--silent" option for LESS compiler.

Also, I believe warning messages should not prevent CSS output from being generated.

Thanks

**Comment by madskristensen** [comment]
Silent means warnings are not produced, right? Perhaps that should just be the default and not be an option?

**Comment by mark-gu** [comment]
RE: "*Silent means warnings are not produced, right?*" - YES

RE: "*Perhaps that should just be the default and not be an option?*" - Warnings are still useful in some cases.

I think what I'm really after is to have CSS output even **with only warnings**. Currently no CSS is generated at all.

I'm suggesting to support "--silent" is really a workaround that no output means successful compilation, hence generating the CSS output. But if you could fix the underlying issue (generating CSS output with only warnings), whether to support "--silent" becomes unimportant.

**Comment by madskristensen** [comment]
What would be an example of something that produces a warning that stops Web Compiler from compiling the file?

**Comment by madskristensen** [comment]
Never mind, I can repro it and a fix is coming...

**Comment by mark-gu** [comment]
Thanks!
