### ISSUE TITLE
Files with changes not being recompiled

### ISSUE THREAD

**Issue by reubenrybnik** [madskristensen/WebCompiler#130]
Commit https://github.com/madskristensen/WebCompiler/commit/b9a50a8543e976df5dd7042cc583fef0eae03a2a uses the input file's last access time to determine whether or not it has changed in src/WebCompiler/Config/Config.cs on line 85. Unfortunately, I observed that last access time was not being updated after I had just saved changes to one of my SCSS files, which was preventing the build from rebuilding it. I did some digging, and found https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290(v=vs.85).aspx, which states that last access time may not be updated for up to an hour after the last access on NTFS file systems and is only the date (not the time) on FAT file systems. Consider updating this to check last modified time in addition to or instead of last access time since that timestamp appears to be set more dependably.

Excerpt from https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290(v=vs.85).aspx:
"Not all file systems can record creation and last access times, and not all file systems record them in the same manner. For example, the resolution of create time on FAT is 10 milliseconds, while write time has a resolution of 2 seconds and access time has a resolution of 1 day, so it is really the access date. The NTFS file system delays updates to the last access time for a file by up to 1 hour after the last access."

**Comment by madskristensen** [comment]
Thanks for the bug report. This is a typo originally. It should always have been LastWriteTime

**Comment by reubenrybnik** [comment]
Thanks for the lightning-fast fix!
