### ISSUE TITLE
.map files are not generated for .scss files.

### ISSUE THREAD

**Issue by mhenry1384** [madskristensen/WebCompiler#134]
Using 
Visual Studio Enterprise 2015 (14.0.23.107.0)
Bundler & Minifier 1.5.113
Web Compiler 1.7.246
Web Essentials 2015 0.5.186

.map files are not generated.  I have sourceMap = true in my compilerconfig.json

{
    "outputFile": "Themes/Chase/Styles/WysiContentArea-Boogly-BooglyBoo.css",
    "inputFile": "Themes/Chase/Styles/WysiContentArea.scss",
    "minify": {
        "enabled": true
    },
    "sourceMap": true,
  },

The .min and .css files are generated but never any map file.  I'm expecting to see a 
WysiContentArea-Boogly-BooglyBoo.css.map.  
But no.

Tried a few different .scss files in my project without success.

**Comment by madskristensen** [comment]
The source maps is base64 encoded and inlined in the file

**Comment by matthewpavkov** [comment]
I also had this problem. I had the source map that was generated by Web Essentials from VS2013 still on the file system, after removing the separate map file, I then started seeing the source map info in Chrome as expected.

**Comment by mhenry1384** [comment]
@madskristensen So it is.  Might want to mention that in the readme though.

**Comment by jkewley** [comment]
This bit me, too during a migration from web essentials. I'd suggest a slight explanation in the ```Readme.md```. You may also want to update the sample ```compilerconfig.json``` at the bottom of the Readme to show the new preferred placement for the ```sourceMap``` setting under ```options```

**Comment by madskristensen** [comment]
Sounds like a great opportunity for a pull request if anyone is interested in updating the readme.md with these changes?
