### ISSUE TITLE
Directory.Delete of Temp Directory (node_modules)

### ISSUE THREAD

**Issue by lg061870** [madskristensen/WebCompiler#135]
I have been playing with the unit tests and most of them fail when trying to delete the node_modules files copied into the local temp directory with "missing part of path for xxxxx"

None of the files in that directory are read-only and they are created under my user directly. I am running as an administrator as well. The only thing I can say is that the resulting paths (for the subdirs) are very very long and it is suspect no#1. 

Is this issue local to me?? work around?

Guillermo

**Comment by madskristensen** [comment]
I haven't heard about this before. What if you delete the **%localappdata%\Temp\WebCompiler1.x.xxx** folder completely and then restart VS?

**Comment by madskristensen** [comment]
Ahh, hang on. I know why. You need to update npm to version 3.3.x. That will create a flat folder hierarchy inside the node_modules folder
