### ISSUE TITLE
Visual Studio 2015 Web Compiler creating two files for minification

### ISSUE THREAD

**Issue by cblaze22** [madskristensen/WebCompiler#139]
http://stackoverflow.com/questions/33250538/visual-studio-2015-web-compiler-creating-two-files-for-minification

**Comment by madskristensen** [comment]
Just make the input and output file the same in the JSON file

**Comment by cblaze22** [comment]
Of course I did that, it just overwrites my original file that is in the same directory with the .min version.

**Comment by madskristensen** [comment]
I don't understand the issue then. The SO post doesn't specify what you are trying to achieve. If you're just wanting to minify a .js file, then you should use the [Bundler & Minifier](https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40) extension for that. The Web Compiler will actually compile the .js file using the Babel compiler first

**Comment by cblaze22** [comment]
Ok Ill try that out, guess I'm not sure what Web Compiler is suppose to do.

**Comment by cblaze22** [comment]
That was it.  Thanks!
