### ISSUE TITLE
Sass sourcemap - no way to specify sourceRoot?

### ISSUE THREAD

**Issue by mhenry1384** [madskristensen/WebCompiler#141]
I have this in my compilerconfig.json

{
"outputFile": "Themes/C/Styles/J/Brand.css",
"inputFile": "Themes/C/Styles/J/Brand.scss",
"sourceMap": true,
}

I see the .scss in Chrome debugger, but when I click on the link for Brand.scss it tries to go to

http://mydomain.com/Themes/C/Styles/Themes/C/Styles/J/Brand.scss
(this also happens in Firefox)

uudecoding the sourcemap in the Brand.css I see

{
	"version": 3,
	"file": "../Themes/C/Styles/J/Brand.css",
	"sources": [
		"../Themes/C/Styles/Jaguar/Brand.scss",

So, I guess there needs to be a way to specify the sourceroot.  But that appears to not be an option.    It's hard to see how sourceMaps could be useful without that.  

If I add the sourceroot by hand, encode the modified sourcemap, and copy it into the css file, then clicking on Brand.scss goes to 
http://mydomain.com/Themes/C/Styles/J/Brand.scss
as I would expect.

**Comment by madskristensen** [comment]
In a few minutes, the CI build is done and you can download it here for testing: http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

Sourcemap options are now all inside the options element in the JSON file

**Comment by mhenry1384** [comment]
Wow, most responsive open source developer ever. :+1:   Thanks!
