### ISSUE TITLE
Math operations in scss with comments in between fail

### ISSUE THREAD

**Issue by sepptruetsch** [madskristensen/WebCompiler#147]
Using 
```css
min-width: 20px /* height */ + 2*5px /* padding */ + 2*1px /*border*/;
```
results in 
```css
min-width: 20px 10px 2px;
```

Using WebEssentials and WebWorkBench this resulted in the correct 
```css
min-width: 32px
```

The comments in between mess it up as 
```css
min-width: 20px + 2*5px + 2*1px; /* height + padding + border */
```
works fine.

Thanks for your time and effort, awesome extension otherwise!

**Comment by madskristensen** [comment]
Please open the issue with [node-sass](https://github.com/sass/node-sass).

It works fine in the official Ruby version of Sass but not in the nodejs based version called node-sass, which is the component this extension uses
