### ISSUE TITLE
Expected a selector for the style rule.

### ISSUE THREAD

**Issue by elitenetdanmark** [madskristensen/WebCompiler#149]
Hello.

When using a SASS statement like seen below, I get "Expected a selector for the style rule" Warning at the line "&-0#....". I can't figure out which selector the system expects?
Seems like a problem with SASS validation?

      .grid {
      @for $i from 1 through 3 {
        &-0#{$i} {
            min-height: 250em;

            @if $i == 1 {
                background-color: $Color01;
            }

            @if $i == 2 {
                background-color: $Color02;
            }

            @if $i == 3 {
                background-color: $Color03;
            }
        }
    }
    }

The output is:

    grid-01 {
     min-height: 250em;
     background-color: #3c3c3c; }

    .grid-02 {
     min-height: 250em;
     background-color: #5f5f5f; }

    .grid-03 {
     min-height: 250em;
     background-color: #d8d8d8; }

(Validated in jigsaw.w3.org) So I cant see why there is a warning.

o_O Bille
www.elitenet.dk

**Comment by madskristensen** [comment]
This is an issue with Visual Studio's Sass editor and not this extension. I've opened a bug on the Visual Studio Web Team to fix this issue. Closing it here. Thanks for the heads up.
