### ISSUE TITLE
'Node' Is not recognized as an internal or external operable program or batch file

### ISSUE THREAD

**Issue by tuliomamute** [madskristensen/WebCompiler#155]
After change my LESS file, on build moment, this message appear for me.

Before install node, this extension work, and, in random time, this error occurs.

I'm using Visual Studio 2015

![image](https://cloud.githubusercontent.com/assets/6129653/11299353/34f31566-8f6d-11e5-8a53-ef4f44fbf79b.png)

**Comment by madskristensen** [comment]
That is very strange since this extension ships node.exe and uses it. Try deleting the folder 
`%localappdata%\temp\WebCompiler1.xx` and restart VS. The extension will then recreate it and put node.exe back on disk

**Comment by madskristensen** [comment]
@tuliomamute Did you try deleting the folder?

**Comment by madskristensen** [comment]
Closed due to inactivity

**Comment by jtmueller** [comment]
I didn't open this issue, but I had the same problem, and deleting the indicated folder and restarting VS did indeed fix it.

**Comment by SMERKY** [comment]
+1 Also worked for me - make sure you exit VS and not just rebuild as the same error appears

**Comment by Erbenos** [comment]
+1 Also worked for me.
