### ISSUE TITLE
Imported files are not being compiled on save

### ISSUE THREAD

**Issue by sashkanz** [madskristensen/WebCompiler#160]
I have a file "main.less" which includes references to other less files:
@import file-1.less
@import file-2.less
@import file-3.less
Every time when I save file-1, file-2 or file-3 I also have to save main.less file manually otherwise it will not save my change I did in one of the above files.
Is there a way to compile and save main.less file automatically when I save one of the file-X.less files?
I guess it is a bug...
My version is 1.8.270, tried also 1.8.277 same thing.

**Comment by bn4z** [comment]
Same problem for me. **file-2.less** imports **file-1.less**. My web page has a reference to **file-2.min.css**.
Saving **file-1.less** does not update **file-2.min.css**.
So I need to constantly swap between file-1 to edit and file-2 to save and see my changes using Browser Link. In my opinion, the real advantage of browser link is to be able to see changes in the browser almost real time without having to move hands away from keyboard.
Is it (or would it be) possible to have an option in compilerconfig.json saying to compile **file-2.less** when **file-1.less** is saved ? In my case, I don't need file-1.min.css. For @sashkanz , I guess it is the same : he only needs to compile main.less when one of the 3 other files is saved. BTW, thanks for the Web Essential extension. It's a must-have :)

**Comment by bn4z** [comment]
I just removed file-1.less from my compilerconfig.json (I realized it was useless when writing my previous comment) and it fixed the issue. When I save file-1, it compiles file-2.
In case it's not very clear, my config file looks like this:
```javascript
[
  //{
  //  "outputFile": "css/file-1.css",
  //  "inputFile": "css/file-1.less"
  //},
  {
    "outputFile": "css/file-2.css",
    "inputFile": "css/file-2.less"
  }
]
```
My HTML uses file-2.css

**Comment by sashkanz** [comment]
@bn4z , thanks for your workaround, worked fine for me but then file-1.css will never be updated ever again and there is always will be a chance of using mistakenly outdated file-1.css file.
Also if you have more @imported files it starts to be more complicated to remember and disable all of them in compilerconfig.json. (I have about 10 of them and keep adding)

Hope this will be fixed soon on one of the nighty builds.
And yeah less compiler is awesome! Thanks to the Web compiler developer!

**Comment by madskristensen** [comment]
By design, any file that is listed in compilerconfig.json will not trigger other .less files to compile. This is by design because there is no logic that can determine the chain of imports and therefore it has to compile every listed .less file. That is slow

**Comment by sashkanz** [comment]
Thanks for your answer, maybe it is a good idea to mention it in your documentation. (How to save automatically the parent file if you save its child)
Basically I just expected the same behavior as on web essentials 2013, when I save imported file I wouldn't expect also that I need to save the parent one. Even if it will take a 1-2 seconds more it is still better then saving all files separately.

**Comment by tgrosh** [comment]
I don't think this should have been closed. This is a feature that existed before under Web Essentials, and should still exist. It should at least be configurable in case there actually is someone who doesnt want it to cascade the compile from the top.

**Comment by gercheq** [comment]
@madskristensen  Without compiling the imported files this plugin is pretty much useless for large scale projects. Is there a way to watch all the files and compile accordingly on file save? If not, should I rely on grunt to do it?

**Comment by marylaureColibri** [comment]
This issue re-appends.
