### ISSUE TITLE
Typo in LESS compilers section in auto generated compilerconfig.json.defaults

### ISSUE THREAD

**Issue by slaneyrw** [madskristensen/WebCompiler#161]
The compilerconfig.json.defaults fle created has typos in the less/compilers section

VS2015 Update 1

**soruceMapRoot** and **soruceMapBasePath**

    "compilers": {
      "less": {
        "autoPrefix": "",
        "cssComb": "none",
        "ieCompat": true,
        "strictMath": false,
        "strictUnits": false,
        "relativeUrls": true,
        "rootPath": "",
        "soruceMapRoot": null,
        "soruceMapBasePath": null,
        "sourceMap": false
      },
    ...
    }

**Comment by madskristensen** [comment]
This has been fixed
