### ISSUE TITLE
Lines ending in '\' ignore last character and carriage return

### ISSUE THREAD

**Issue by blabute** [madskristensen/WebCompiler#162]
It seems when a line in the .scss file ends with a backslash, the backlash and the carriage return are ignored.

.scss 
/*---------------------------------------------*\
    TEST
\*---------------------------------------------*/

Resulting .css
/*---------------------------------------------*    TEST
\*---------------------------------------------*/

Adding another character to the end will give the expected result as seen below.
.scss 
/*---------------------------------------------*\\
    TEST
\*---------------------------------------------*/

Resulting .css
/*---------------------------------------------*\\
    TEST
\*---------------------------------------------*/

**Comment by madskristensen** [comment]
That's how the sass compiler works. The issue should be raised with LibSass https://github.com/sass/libsass
