### ISSUE TITLE
Error in compilerconfig.json

### ISSUE THREAD

**Issue by ropstah** [madskristensen/WebCompiler#166]
I'm suddenly getting this message: "there is an error in the compilerconfig.json file. this could be due to a change in the format after this extension was updated." when saving my scss file. I tried uninstalling WebCompiler and installing the latest build (Web Compiler v1.9.286.vsix) but still getting the same error.

The output window shows the following.

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WebCompiler.CompilerService.Initialize() in C:\projects\webcompiler\src\WebCompiler\Compile\CompilerService.cs:line 95
   at WebCompiler.CompilerService.GetCompiler(Config config) in C:\projects\webcompiler\src\WebCompiler\Compile\CompilerService.cs:line 37
   at WebCompiler.ConfigFileProcessor.ProcessConfig(String baseFolder, Config config) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 147
   at WebCompiler.ConfigFileProcessor.Process(String configFile, IEnumerable`1 configs, Boolean force) in C:\projects\webcompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 44
   at WebCompilerVsix.CompilerService.<>c__DisplayClass6_0.<Process>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 60

**Comment by phrei** [comment]
I get the same error message  "there is an error in the compilerconfig.json file. this could be due to a change in the format after this extension was updated." when saving a LESS file while debugging my web project.

When I stop the debugger, I can save the LESS file with no problem.

I don't see an exception in the output window though - like ropstah does.

**Comment by matthewpavkov** [comment]
@phrei Have you tried the latest `1.10.300` version of Web Compiler? Also, you may want to try restarting Visual Studio in between your tests.

**Comment by phrei** [comment]
@matthewpavkov I did install 1.10.300 today and I have since restarted VS multiple times. I can't even edit js-Files anymore either without getting this error. It is so annyoing that I had to deactivate Web Compiler :-(

**Comment by matthewpavkov** [comment]
@phrei Disabling Web Compiler prevents the problem? Try disabling all extensions except Web Compiler and see if you can still reproduce it. Did you try regenerating the `compilerconfig` files? Are you sure your configs are valid? You said you were using it for LESS, if you're not using it for JavaScript, then try removing those sections from the `compilerconfig` file(s).

**Comment by phrei** [comment]
@matthewpavkov Yes disabling prevented the problem. I didn't have any JavaScript sections in compilerconfig - only "inputFile" and "outPutFile" JSON Objects as follows:

[
  {
    "outputFile": "app/css/file1.css",
    "inputFile": "app/css/file1.less"
  },
  {
    "outputFile": "app/css/file2.css",
    "inputFile": "app/css/file2.less"
  }
]

What I did this morning was open the compilerconfig.json.defaults - which looks as follows:

{
  "compilers": {
    "less": {
      "strictMath": false,
      "strictUnits": false,
      "relativeUrls": true,
      "rootPath": ""
    },
    "sass": {
      "indentType": "space",
      "indentWidth": 2,
      "outputStyle": "nested",
      "Precision": 5
    },
    "coffeescript": {
      "bare": false,
      "runtimeMode": "node"
    }
  }
}

I edited it and saved it (it still looks the same). Now I don't have the error anymore.

**Comment by ygrenier** [comment]
Hi, same problem, but I found more precisions.

In the output an exception is displayed
```
System.Runtime.InteropServices.COMException (0x80020003): Membre introuvable. (Exception de HRESULT : 0x80020003 (DISP_E_MEMBERNOTFOUND))
   à EnvDTE.Project.get_FullName()
   à WebCompilerVsix.ProjectHelpers.GetRootFolder(Project project) dans C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:ligne 61
   à WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) dans C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:ligne 98
```
It's on french system so "Membre introuvable" is "Member not found".

The only change I done is adding an import of a LESS file. When editing not problem. When I debug the website:
- I change and save a file (the imported or the importer file) 
- the error is displayed "There is an error in the compilierconfig.json file. ...". 
- the LESS file is not compiled
- the compilerconfig.json is opened in VS
- when I save the compilerconfig.json file (whithout change) the LESS file is compiled

**Comment by Stompf** [comment]
Also getting the same error as ygrenier error message in english:

2016-01-28 10:54:48: System.Runtime.InteropServices.COMException (0x80020003): Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
   at EnvDTE.Project.get_FullName()
   at WebCompilerVsix.ProjectHelpers.GetRootFolder(Project project) in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 61
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 98

**Comment by madskristensen** [comment]
@Stompf What type of project? ASP.NET WebForms, Cordova, or...?

**Comment by Stompf** [comment]
[TypeScriptHTMLApp1.zip](https://github.com/madskristensen/WebCompiler/files/108675/TypeScriptHTMLApp1.zip)

It's a MVC project. I can reproduce it with the project i attached in the zip file (TypeScriptHTMLApp1.zip). Just start the code from visual studio and try to change something in the app.less file while in debug mode and you should get the error. 

I'm using Visual Studio 2015 Update 1.

**Comment by madskristensen** [comment]
@Stompf Thanks for the repro project. I still wasn't able to reproduce the issue. Here's what I did:

1. Opened the project in VS2015 Update 2
2. Hit F5 to run the web project and enter debug mode
3. Made a change to app.less and saved the fil

Result was that the compilation happened correctly and no errors were produced. Am I missing something from the repro steps?

**Comment by madskristensen** [comment]
@Stompf I can repro it now. Had to use Internet Explorer because of they way VS attaches to it
