### ISSUE TITLE
Sass/Less-Files not recompiling when imported file has been changed

### ISSUE THREAD

**Issue by msandberger** [madskristensen/WebCompiler#169]
Hello!

The scenario is a file Main.scss which includes a file Variables.scss.

When the included file is changed, I would expect that the Main-file is automatically recompiled.
That does not happen, not even when I do a "Recompile all files in solution".
Only when I manually save the Main-file or the compilerconfig.json, then the main-output is updated.

This behaviour can be observed with both LESS and SASS files. 
There is closed issue which sounds similar: #125 

I am using Visual Studio Enterprise 2015 with Update 1. Also WebEssentials 2015.1 and WebCompiler 1.9.286. Even tried disabling Web Essentials and Resharper, did not change anything.

I attached a simple VS-solution to reproduce the issue: Changing a value in the Variables-file and saving that file does not trigger a recompile of the Main-file:
[WebCompilerIssueRepro.zip](https://github.com/madskristensen/WebCompiler/files/74744/WebCompilerIssueRepro.zip)

Thanks & Happy new year!

**Comment by PaulVrugt** [comment]
We have exactly the same problem. We are still using visual studio 2015 and cannot migrate to 2015 until this issue is solved. We have loads of dependencies between scss files, and when saving a scss which is imported by other scss files, the other scss are not recompiled.

**Comment by msandberger** [comment]
I just found out that this issue only occurs if the included file is listed in the compilerconfig.json.

The following constellation works as expected:
* _Main.scss_: Listed in compilerconfig, imports _Variables.scss_
* _Variables.scss_: NOT listed in compilerconfig
* Edit/Save _Variables.scss_ -> Main-Output is updated

So, including only your actual target files in the compilerconfig.json and leaving out all the imports seems like a feasible workaround for the time being. But if you have files which are both imported and used standalone, the described solution does not work (because there is no output generated for files which are not listed in compilerconfig).

**Comment by PaulVrugt** [comment]
This issue has been fixed in the latest commit

**Comment by riddla** [comment]
"Latest commit" meaning that ... in which version will this fix be in? I'm running version `1.10.300` and saving an `@import`ed SASS file does not trigger the re-compulation of the main file.

**Comment by PaulVrugt** [comment]
If you still have the issue in 1.10.300, please attach the main file and file with the dependency to a post here and we can determine why the dependency is not recognized.
