### ISSUE TITLE
Source map reference wrong?

### ISSUE THREAD

**Issue by pdeffendol** [madskristensen/WebCompiler#17]
I'm using the following configuration:

```  
{
  "outputFile": "Content/licenses/Demo/styles.css",
  "inputFile": "Content/licenses/Demo/styles.scss",
  "minify": {
    "enabled": false
  },
  "includeInProject": true,
  "sourceMap": true,
  "options": {}
}
```

The generated .css file contains the following at the end:

```
/*# sourceMappingURL=styles.scss.map */
```

However, the generated source map has the filename `styles.css.map`. (Note the different extension.)

**Comment by madskristensen** [comment]
Gotcha. Fix coming asap

**Comment by madskristensen** [comment]
Build 1.0.45 will be ready for testing in a few minutes here: http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

Can you please try it and let me know if it fixed the issue for you?

**Comment by pdeffendol** [comment]
The filenames match up now, and the source map references are working in Firefox.  (Not working in Chrome but that's an external issue.)

Thanks!

**Comment by madskristensen** [comment]
That's great to hear. Thanks for the bug report and testing. Please keep opening bugs if you find any more

**Comment by Mellbourn** [comment]
@pdeffendol It is not working in Chrome for me either. What did you mean by "that's an external issue"? How did you solve it?
Thanks!

**Comment by pdeffendol** [comment]
@Mellbourn, by "external issue" I mean it's likely a Chrome problem and not WebCompiler.  I actually haven't looked into it further.
