### ISSUE TITLE
How to skip ParseError errors?

### ISSUE THREAD

**Issue by UweKeim** [madskristensen/WebCompiler#170]
I need this code inside my resulting CSS file:

```less
// IE FIX - THIS MEDIA QUERY ONLY FIRES ON IE9+
@media screen and (min-width:0\0) {
    /* ... */
}
```

Unfortunately, this produces an error upon saving:

> ParseError: Missing closing ')' in YourFile.less

**My question:**

Is there any workaround like a pragma or comment to tell WebCompiler to simply write the (intentionally) erroneous code to the resulting CSS file?

**Comment by madskristensen** [comment]
I don't know if you're writing LESS or Sass files but this extension uses node.js modules for compiling. So please file the bug/suggestion with either the **libsass** or **less** projects on github

**Comment by UweKeim** [comment]
I'm writing LESS. I'll do as suggested. Thank you.

**Comment by UweKeim** [comment]
Is this the correct repository: https://github.com/less/less.js?

**Comment by madskristensen** [comment]
Yes, I believe it is

**Comment by UweKeim** [comment]
I solved it by [escaping](http://lesscss.org/features/#features-overview-feature-escaping) the relevant part:

```less
// IE FIX - THIS MEDIA QUERY ONLY FIRES ON IE9+
@media screen and (min-width:~"0\0") {
    /* ... */
}
```

To quote the documentation:

> Escaping allows you to use any arbitrary string as property or variable value. Anything inside `~"anything"` or `~'anything'` is used as is with no changes except interpolation.
