### ISSUE TITLE
An exception throws when try to open a view (cshtml)

### ISSUE THREAD

**Issue by emiliogg84** [madskristensen/WebCompiler#174]
The extension causes that razor code editor raise an exception ("Object reference not found") and not opens view files (cshtml)... 

The web application in question does not have any sass or less files... just controllers, views, js, and pure css..

**Comment by madskristensen** [comment]
I'm pretty sure this extension doesn't cause it since no HTML editor APIs is being used. Have you tried to uninstall this extension to see if it still happens?

**Comment by madskristensen** [comment]
Closing
