### ISSUE TITLE
CSS is not generated if changes done in a 2-level child .less file

### ISSUE THREAD

**Issue by miksh7** [madskristensen/WebCompiler#175]
After installing 1.10.297 the css file generation is not triggered if a change is done in a 2+ level of child less file.
E.g. base.less contains a list of less files to import:
@import "variables";
@import "layout";
@import "app";

The change is base.less triggers the css generation but a change in layout.less does not.

**Comment by bryjohnson** [comment]
I am also experiencing this problem.  This worked ok in 1.9.x

**Comment by madskristensen** [comment]
@PaulVrugt It seems like it broke with the PR for dependency resolution. Do you have time to take a look, please?

**Comment by PaulVrugt** [comment]
I'll take a look tomorrow

**Comment by madskristensen** [comment]
Thanks Paul

**Comment by madskristensen** [comment]
This is fixed

**Comment by bryjohnson** [comment]
Works great again.  Thanks.
