### ISSUE TITLE
"Error in the compilerconfig.json file" after updating

### ISSUE THREAD

**Issue by goleafs** [madskristensen/WebCompiler#179]
I updated the Web Compiler yesterday 

Whenever I try to save any file (even .js) in the solution now I am getting:
"There is an error in the compilerconfig.json file.  This could be due to a change in the format after this extension was updated."

In addition I noted this error in the output:
2016-01-21 8:25:32 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebCompilerVsix.ProjectHelpers.GetRootFolder(Project project) in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 61
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 98

This file/path does not even exist.. not sure why it is looking there....

**Comment by Nick0n** [comment]
Same problems happened to me : /

**Comment by christopherbauer** [comment]
Thirded, since yesterday:

1/21/2016 7:56:15 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebCompilerVsix.ProjectHelpers.GetRootFolder(Project project) in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 61
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in C:\projects\webcompiler\src\WebCompilerVsix\CompilerService.cs:line 98

**Comment by josephpspiteri** [comment]
My web compiler was set to auto update :( and now sometimes, when I save, this error is popping up. But the most annoying thing is that it is NOT auto compiling. At the bottom left status bar it shows as "Compiling... etc & Compiling Successful", but in reality it is not. 

As an interim solution, any ideas on how to re-install a previous version?

**Comment by angeliquejw** [comment]
Also confirming this issue; experienced every time I attempt to save a SCSS file.

**Comment by josephpspiteri** [comment]
Anyone struggling with this, I downloaded version 1.2.118 (and disabled the auto-update extension) and it is working fine now. Download link: https://github.com/madskristensen/WebCompiler/releases/tag/v1.2

**Comment by PaulVrugt** [comment]
This has to do with the dependency fix in the latest version. For some reason it cannot determine the project root directory. Mads might be able to shed some light on why the project root directory cannot be located

**Comment by madskristensen** [comment]
Please try the CI build 1.10.298 here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

It's ready in a few minutes

**Comment by josephpspiteri** [comment]
All working fine for me. Thanks for the quick fix, much appreciated.

**Comment by crystalbyte** [comment]
Just installed version 1.10.310 and I get the same NulReferenceException when a compilation is triggered. We use .NET 4.6 in an MVC5 project.
