### ISSUE TITLE
Less dependent compilation not working when using @import (once)

### ISSUE THREAD

**Issue by torerikk** [madskristensen/WebCompiler#180]
Compilation of dependent .less files doesn't happen when using `@import (once)`, it works fine when using `@import` with out the (once).

**Comment by PaulVrugt** [comment]
True, support for This hasn't been added yet but This should be fairly easy

**Comment by madskristensen** [comment]
Please help test CI build 1.10.299 which is ready in a few minutes here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by torerikk** [comment]
Works great! Thank you so much!
