### ISSUE TITLE
Parent SCSS files not compiling when an imported SCSS file is saved.

### ISSUE THREAD

**Issue by travislaynewilson** [madskristensen/WebCompiler#182]
A recent update seems to have broken this feature, as it was working fairly recently. When I'm editing a .scss file (eg. _buttons.scss) and save my changes, the parent .scss file it's imported into is not compiling automatically as it once was. There are no errors, and the status bar flashes that it "compiled successfully". The compilation seems to be happening instantaneously, whereas the  parent .scss file takes a second or two to compile normally.

When I save the parent .scss file, it compiles normally.

**Comment by madskristensen** [comment]
Are you using version 1.10.300?

**Comment by travislaynewilson** [comment]
My apologies, I should have provided the version info.

I was using the following when I submitted my issue:
   Visual Studio Community 2015, v.14.0.24720.00 Update 1
   WebCompiler v.1.10.297

I restarted Visual Studio again to be sure. It updated to v.1.10.300, and everything appears to be working again as expected!

Thank you sincerely for your prompt response! Great work!

**Comment by madskristensen** [comment]
Awesome. Glad it worked out

**Comment by angeliquejw** [comment]
I have been encountering this same issue. I'm using
Visual Studio Professional 2015 v 14.0.24720.00 Update 1
Web Compiler v 1.10.303
