### ISSUE TITLE
Compiler with task runner does not parse SASS if there is no space after hyphen delimiter 

### ISSUE THREAD

**Issue by smartmeter** [madskristensen/WebCompiler#183]
While running a compile from the task runner, it complains about syntax. 

**Issue:** the syntax is fine, but *the lack of space right after the *hyphen* is tripping the compiler/parser.*

for e.g. `Invalid CSS after "...ht-green:#f416cb": expected 1 selector or at-rule, was "{}"`

**Solution:** When I change/add space to that `ht-green: #f416cb` notice the addition of space right after hyphen works fine, it compiles fine. I verified this with Kaola and compass, they do not have this issue. 

Parser needs to parse after hyphen and not expect space

**Comment by madskristensen** [comment]
Please file the bug with the `node-sass` project on GitHub. That's the compiler this extension uses
