### ISSUE TITLE
Compiler configuration error pops up during debugging

### ISSUE THREAD

**Issue by wmjordan** [madskristensen/WebCompiler#186]
After upgrading to version 1.10.300, I met with this situation quite many times. 
I had a project using Web Compiler to compile SCSS file into CSS files.
The Web Compiler could pop up while I was debugging in VS and saving a JavaScript file, and the compiler complaining that "_There's an error in the compilerconfig.json file. This could be due to a change in the format after this extension was updated._"
I was not compiling JavaScript files.
The dialog would not pop up if VS was not debugging the project.

I tried to remove the _compilerconfig.json_ and those compiled files, and recreate them by executing the Compile command on them in VS 2015.1. The bug still occurred

**Comment by madskristensen** [comment]
Just fixed this with latest commit
