### ISSUE TITLE
VS 2105 Error	LNK1104	cannot open file 'opencv_world310d.obj'	CannyStill?

### ISSUE THREAD

**Issue by Sandeepkriss** [madskristensen/WebCompiler#188]
Hello Everyone,
I'm going through this problem in vs2015 with opencv3.1.0. when I'm trying to run the program. I'm getting error "System cannot find the file specified .exe". Based On suggestion i tried the F11 & F10 and the following errors pop up please have a look on attachments and give some suggestions. Thank you 

![f11](https://cloud.githubusercontent.com/assets/16983194/12879176/dea20f9e-ce48-11e5-87c4-d3b5d87317d6.png)

**Comment by madskristensen** [comment]
How does this relate to Web Compiler?
