### ISSUE TITLE
Inconsistent compiling with relative output directory path

### ISSUE THREAD

**Issue by s-whaley** [madskristensen/WebCompiler#198]
I need to compile my less files to a directory outside my web project root. This typically works fine although sometimes the files get compiled(on save) to the root of the web project. I cannot reliably reproduce the problem(e.g. it's not a specific file, or not dependent on the number of times a file is compiled), however it does happen quite often. This causes issues with our CI server because there are unexpected files in the root of the project. I can provide project information from the extensibility tools if needed. This occurs with .less and .js files and has not been limited to one solution. 

I did a quick search through closed issues and although I found several relative URL issues, they seemed to be specific to URLs in a .less file. 

Example of my compilerconfig.json file.
```json
[
  {
    "inputFile": "Areas/PROJECTNAME/less/main.less",
    "outputFile": "../sandbox/Website/Areas/PROJECTNAME/css/main.css",
    "sourceMap": true
  }
]
```
![capture](https://cloud.githubusercontent.com/assets/7151245/13267701/46d05cea-da44-11e5-871b-a50d92498217.PNG)

**Comment by madskristensen** [comment]
Like you've added the `sourceMap` option, you should also add one for `includeInProject` and set it to false.

**Comment by s-whaley** [comment]
I think that fixed it. I do not see that option in the defaults, although I see it in the readme now. I was not aware that was an option. Thanks!
