### ISSUE TITLE
LESS calc() incorrect with variable units.

### ISSUE THREAD

**Issue by esargent** [madskristensen/WebCompiler#200]
### Installed product versions
- Visual Studio: 2015 Professional, Update 1
- This extension: 1.10.306

### Description
compiling LESS files with a calc() function which uses different units results in an incorrect simplification. For example - calc(76vh - 71px) ==> calc(5vh)

### Steps to recreate
1. Create a less file
2. Add lines, such as
     .somestyle{height: calc(76vh - 71px);}
     .somestyle2{height: calc(72vh - 71px);}
3. Save/compile.
4. Examine the resulting css file to see that the formulas have been simplified - but are now incorrect.

### Current behavior
simplifying the calc() results in unexpected and unwanted behavior.

### Expected behavior
calc() should remain the same as specified. units like 'vh' can't be known until runtime and are device dependent.

**Comment by Mikey1982** [comment]
It's a LESS compiler feature/issue (not WebCompiler): you have to protect you calc expression with ~"expression". F.e :  ~"calc(76vh - 71px)"
Otherwise LESS compiler tries to calculate the expression inside calc.

**Comment by madskristensen** [comment]
Thanks for the explanation @Mikey1982. Closing issue
