### ISSUE TITLE
Removing the batch file from itself causes the Error "Insert the diskette that contains the batch file and press any key when ready."

### ISSUE THREAD

**Issue by sguryev** [madskristensen/WebCompiler#206]
### Installed product versions
- Visual Studio: 2015 Update 2
- This extension: 1.10.306

### Description
Removing the batch file from itself causes the deadlock which holds the directory and prevent the further work.

### Steps to recreate
1. Run the Visual Studio with the WebCompiler extension installed

### Current behavior
Process.WaitForExit() method never returns because of the deadlock in the prepare.cmd file.

### Expected behavior
Process should be ended successfully.

![clip2net_160405142501](https://cloud.githubusercontent.com/assets/6978458/14280640/a8a0eb7e-fb3c-11e5-8877-e338d44fd635.png)

**Comment by sguryev** [comment]
As you see this method call is situated before the "log.txt" file creation. 
![clip2net_160405144321](https://cloud.githubusercontent.com/assets/6978458/14280661/c8e5367e-fb3c-11e5-9fc8-972ea440a3db.png)
So this CMD process will hold the WebCompiler directory for always and will not allow to run this code during the next initialization:
![clip2net_160405144504](https://cloud.githubusercontent.com/assets/6978458/14280706/0e1e8178-fb3d-11e5-83f1-497f978e16a4.png)

As the result: exception on the next initialization:
![84ce7-clip-63kb](https://cloud.githubusercontent.com/assets/6978458/14280725/3ac07f4c-fb3d-11e5-942c-c795a0b5e410.png)

**Comment by sguryev** [comment]
Also could you please describe why does the master branch have the "**1.4.166**" version and create the the _WebCompiler1.4.166_ version but the published extension creates the _WebCompiler1.10.306 _folder
![clip2net_160405144954](https://cloud.githubusercontent.com/assets/6978458/14280807/cd89b28a-fb3d-11e5-8c9d-bc53ee68276a.png)

**Comment by madskristensen** [comment]
1.4.166 is being replaced by the CI build version number by the CI server

**Comment by sguryev** [comment]
@madskristensen OK, got it! I have been trying to regenerate the LESS files for last two days. Finally I have found the way: I have to add the empty _log.txt_ file to the WebCompiler folder manually after starting the Visual Studio. No I can regenerate the LESS file based on the _compilerconfig.json_ file but only through the _Task Runner Explorer_. No one right mouse button option doesn't work (neither saving LESS file directly, nor selecting **Re-compile file** on LESS or on the _compilerconfig.json_ file.). Also I have to click the **Remove output files** option first otherwise it says _"Done compiling"_ and does nothing.

**Comment by sguryev** [comment]
The source of the issue are values of the TEMP and TMP values in the system variables. 
![clip2net_160406023600](https://cloud.githubusercontent.com/assets/6978458/14301661/47e90d1e-fba2-11e5-9330-39c2a733a671.png)
I had the _B:\_ value for both previously. Now I have the junction instead of the _%USERPROFILE%\AppData\Local\Temp_ folder. 

It's interesting that _B:\Temp _or _S:\_ works good. But the root of the B drive is a problem.
