### ISSUE TITLE
SCSS Compiler modifying URLs

### ISSUE THREAD

**Issue by JasonKaz** [madskristensen/WebCompiler#207]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.10.306

### Description
This happened after upgrading to VS2015 and away from Web Essentials 2013. Not sure if this is something I can configure currently, but relative URLs in SCSS are being modified when they are compiled, which breaks the reference to the file. It may have to do with my folder structure, but I'd rather not change that and just have the compiled code look exactly the way I expect it.

### Current behavior
SCSS:
```
.glyphicon-blue {
    background-image: url(../../assets/images/glyphicons/glyphicons-halflings-blue.png);
}
```

CSS:
```
.glyphicon-blue {
  background-image: url(../images/glyphicons/glyphicons-halflings-blue.png); }
```

Notice the stripped off "../assets".

### Expected behavior
It should not try to fix my URL and output it exactly  as I have it in my SCSS.

**Comment by nicholashead** [comment]
@JasonKaz is this because you don't have `"relativeUrls"` set to `false` in `compilerconfig.json.defaults` ?

**Comment by JasonKaz** [comment]
No, it is currently set to false.

**Comment by JasonKaz** [comment]
So after looking through the source code for the extension, it is meant to be reading from compilerconfig.json, not compilerconfig.json.defaults. The documentation did not make this clear at all.

My current compilerconfig.json:
```
[
  {
    "outputFile": "assets/css/app.css",
    "inputFile": "assets/css/app.scss",
    "minify": {
      "enabled": true
    },
    "options": {
      "sourceMap": true,
      "relativeUrls": false
    }
  }
]
```

**Comment by Bartmax** [comment]
Thank you @JasonKaz documentation is indeed not clear at all.
