### ISSUE TITLE
BuildWebCompiler 1.10.310 errors with "invalid property name" when trying to build SASS files

### ISSUE THREAD

**Issue by Jevonius** [madskristensen/WebCompiler#208]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: BuildWebCompiler.1.10.310

### Description
Upgraded from an older version (1.10.300) yesterday to .310 and now receive the error "invalid property name" when trying to build during our build process. The expected CSS files are not created.
Building manually using WebCompiler Add-in(1.10.306) completes successfully.
Downgrading BuildWebCompiler to 1.10.306 also stops the error happening.

### Steps to recreate
I haven't had time to break this down to a simple reproduction project. We have a master SCSS file which imports lots of partial files. There is a second 'master' SCSS file which tweaks a variable and then imports the other. Both files fail to build, with the same error, both on the same line.
Secondary issue is that the given line number is meaningless - double-clicking the entry in Error List doesn't take you anywhere helpful, so it's unclear exactly what's causing the problem.

Is there a way to make the tool output a log file I can attach to help diagnose? If I get time I'll try and reproduce with a simple project.

**Comment by Jevonius** [comment]
I've had a bit more of a look at this; comparing BWC 306 to 310, there are a lot of changes in the resource file Node.node_modules.7z in WebCompiler.exe (which if I understand the link correctly means that an updated version of the WebCompiler VSIX would show the same issue?).

It looks like some of the node packages are no longer being included, some new ones are, and somewhere along the line it's broken something. As this point I hit the edge of my knowledge (and time to dig deeper), but hopefully this helps a little.

I'll try and find some time tonight to identify exactly what it is in our sass file(s) causing the issue - maybe we're trying to do something that's been deprecated!

**Comment by Jevonius** [comment]
I have finally had the chance to look into this in more depth, and narrow down the problem with a simple demo. The problem remains in .312. Given a .scss file with the contents:
``` scss
$btn-background   : (
  'primary'       : '#8DC9A0',
  'highlight'     : '#ffffff'
);

.button {
  @each $key, $value in $btn-background {
    &.-#{$key} {
      border: none;
      text-transform: uppercase;
      color: #{$value}
    }
  }
}
```
WebCompiler fails to compile it, giving the error `invalid property name`. The line that causes the error is: `&.-#{$key} {`. Adding a prefix before the hyphen (e.g. `&.s-#{$key} {`) stops the error. This workaround also works: https://github.com/sass/libsass/issues/438#issuecomment-50735729

I am a sass novice but as far as I can tell this syntax is valid, and the problem lies between WebCompiler and node-sass. The same snippet compiles fine with Ruby Sass, SassC and the same version of node-sass used in WebCompiler .312 when called directly.

**Comment by madskristensen** [comment]
This is a libsass issue which is the component that node-sass uses. Please raise the bug on their end and I'll ship an update to Web Compiler with the latest node-sass bits as soon as they have resolve it

**Comment by Jevonius** [comment]
Hi @madskristensen,
I did consider that it might be an issue with the tools WebCompiler used, so spent quite a lot of time trying to work out where the problem was occurring. As I said in the last paragraph of my previous post, the same chunk of code compiled fine in the latest versions of [Ruby] Sass, SassC (compiled from source) and also node-sass pulled from npm - the same version that .312 is using. It worked fine in all of them, so the problem does appear to be caused by WebCompiler somehow.

I've just had a look at https://github.com/madskristensen/WebCompiler/blob/119c2c003196d3d395383bcfd5638d3ad22b0333/src/WebCompiler/Compile/SassCompiler.cs and can't see anything obvious that would cause a variation, but as I say the same version of node-sass stand-alone works and compiles the snippet fine.

**Comment by madskristensen** [comment]
Ahh, ok. So if it works in the node-sass when executing it on the command line, then it must be an issue with this extension. I'll reopen the bug

**Comment by Jevonius** [comment]
Thanks - I'm just having a look at it now to see if I can replicate with the node-sass from .312, extracting from the exe. I can't see anything obvious at fault glancing at how WebCompiler calls it, so will keep digging.

**Comment by Jevonius** [comment]
Ok....

I don't think it's a bug in WebCompiler, but I don't know how to diagnose it further - current conclusion is that it's a Node bug, which seems unlikely! :).
I extracted the node packages from .312 and got the same error running manually from the command line. However, diffing against the same node-sass folder from my local Node install, the only difference is the `node_modules\node-sass\vendor` folder - I've got an x64 install, so a vendor folder of `win32-x64-46` whereas those in WebCompiler are the x32 equivalents.

At a guess, at this point the problem /does/ appear to be with node-sass, and this issue should be closed (sorry for the back-and-forth!). Any suggestions for how I could diagnose it further are very welcome! :)

**Comment by Jevonius** [comment]
Hi @madskristensen,

Sorry to re-open this (the dangers of a node newbie trying to debug an issue!), but it does actually seem to be a fault with the WebCompiler build process. From what I can tell, although most of the node-sass files being included in WebCompiler are the latest 3.7.0, the actual binary that does the heavy lifting is still only the one from 3.2.0 (specifically https://github.com/sass/node-sass-binaries/blob/318f069b50241318ec77adbe750a092897923c5b/win32-ia32-14_binding.node). It looks like whatever process updates the node-sass version when you build WebCompiler isn't also updating the binary version.

**Comment by madskristensen** [comment]
@Jevonius That is brilliant, sir! I didn't think of that. I'll update it and kick of a CI build. Stay tuned...

**Comment by madskristensen** [comment]
Ok, please help test the new sass binding in the latest [CI build](http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/)

**Comment by Jevonius** [comment]
Yup, that seems to have got it! Great stuff, thanks! :)
