### ISSUE TITLE
Support for RECESS [idea]

### ISSUE THREAD

**Issue by Jogai** [madskristensen/WebCompiler#21]
To display some warnings about the quality, see https://github.com/twitter/recess

**Comment by GProulx** [comment]
Hi, as pointed out by Mads [on another suggestion](madskristensen/WebCompiler/issues/4), WebCompiler includes only tools that are available in .Net to prevent the use of node.js that cause instability problems with Web Essentials 2013.

**Comment by madskristensen** [comment]
As mentioned in capital letters on the repo of Recess, it is no longer maintained and doesn't work on newer versions of the LESS compiler
