### ISSUE TITLE
Saving a SASS Partial no longer recompiles the main SASS file

### ISSUE THREAD

**Issue by DaveRooney1** [madskristensen/WebCompiler#215]
### Installed product versions
- Visual Studio: 2015
- This extension: got the latest as of today from http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

### Description
When saving a partial sass file there are no errors, the file saves, but the main site.scss now does not compile. this was fine as of 2-3 month ago. I came back to an old project that needed css updates and was at first shown the error "There as an error in the compilerconfig.json file. This could be due to a change in the format after this extention was updated" in a dialog window. regenerating the compilerconfig file fixed this but now the partials do not trigger updates. Instead I need to save the partial and then recompile the main SASS file.

This issue does not stop me from working but is still rather annoying. Thanks.

### Steps to recreate
1. Create a Sass Partial file.
2. Import partial into a main sass file.
3. run site
4. update the partial and save the file.
5. css does not update when refreshing the page int he web browser.
6.recompiling the main.scss is the only way to update the css.

**Comment by DaveRooney1** [comment]
This is still an issue to be fixed, but I have given the reason why it is happening on a previous issue: https://github.com/madskristensen/WebCompiler/issues/197.

> Ok, I figured it out.

Short answer: 
Remove all comments that are on the same line as an @import within SASS files.

Long answer:
The SassDependencyResolver.cs class (method UpdateFileDependencies(string path)) has a regular expression that searches all sass files for @import text and uses the results to map what files that are dependent on each other. Unfortunately there is nothing that strips away comments that are on the same line as the @import text. so the regular expression would return the comment instead of the name of the sass file to import. I'm am not the best with Regular Expressions and have been trying to figure this issue out far too long. So I though I would pass on what I found so someone with better Regex knowledge could make the fix! any way hope this helps those that had the same issue!

**Comment by madskristensen** [comment]
@DaveRooney1 Thanks for the investigation. Can you please paste in the lines containing both `@import` and the comments that reproduces this issue?

**Comment by DaveRooney1** [comment]
Hi, Below is an example of an import at the top of a main.scss:
`@import "Partials/bootstrap-variables";           // Bootstrap overrides`

The code in your WebCompiler would look for a Partial named "Bootstrap overrides" instead of "bootstrap-variables". I believe this is the Regex as I stated in my other comment but I could be wrong.
