### ISSUE TITLE
Nice to have: Add colon after selecting intellisense-property

### ISSUE THREAD

**Issue by jessetinell** [madskristensen/WebCompiler#216]
In these examples I type: "wi" and hit the enter-key. In the css-file I automatically get the colon efter the property name. But in a sass-file (with Webcompiler installed) I don't.
This is a nice feature for fast typing. 

.css
![89f9a945070769335cbd807575ffd8d4](https://cloud.githubusercontent.com/assets/2527882/15072453/1fd4dc0a-1393-11e6-8ed9-e23c0fe529f5.gif)

.scss
![e70023c2ee414214431bd44dcc288f29](https://cloud.githubusercontent.com/assets/2527882/15072551/cf01bb58-1393-11e6-989d-fce60fb53d79.gif)

I'm just guessing it's a Webcompiler-thing. I've never developed an extension for Visual studio so close this "issue" if I'm wrong.

**Comment by madskristensen** [comment]
This is not a Web Compiler thing. It's in VS itself
