### ISSUE TITLE
Do not compile sass modules

### ISSUE THREAD

**Issue by gonace** [madskristensen/WebCompiler#219]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.11.312

### Description
Is there a way not to compile sass modules per default? The only way I found is to add every module in the compilterconfig.json

**Comment by madskristensen** [comment]
Yes, don't add partials to compilerconfig.json. Only add the files that needs to be compiled into an output css file

**Comment by StephenKoller** [comment]
As Mads said, you only need add your main file that imports the rest of your modules, e.g.

style.scss:
`
// Utilities
@import "utilities/colors";
@import "utilities/fonts";
@import "utilities/reset";
@import "utilities/shame";`

compilerconfig.json:
`[
  {
    "outputFile": "Content/style.css",
    "inputFile": "Content/style.scss"
  }
]`

The only downside to this is that Intellisense doesn't recognize variables / mixins / etc shared between modules and throws a bunch of warnings.
