### ISSUE TITLE
Unquoting SASS Interpolated Values Fails

### ISSUE THREAD

**Issue by cshtsui** [madskristensen/WebCompiler#221]
### Installed product versions
- Visual Studio: Community 2015
- This extension: 1.11.312

### Description
Unquoting does not work with SASS interpolation. Basic unquoting seems to work.  I've been using WebCompiler on my project for months with no issues prior to today 

 I encountered this problem trying to compile my project which uses Foundation 6.2.1. Specifically the util/_selector.scss partial has a function that unquotes an interpolated SASS variable. I've reduced the problem for this issue: 

### Steps to recreate
Compile the following .scss file:
$type: hello;
.foo {
	content: unquote("\'#{$type}\'");
}
.bar {
	content: unquote("\'text\'");
}

### Current behavior
The output from the recreation steps is:
.foo {
  content: \'hello\'; }

.bar {
  content: 'text'; }

### Expected behavior
.foo {
  content: 'hello'; }

.bar {
  content: 'text'; }

**Comment by madskristensen** [comment]
This must be an issue from the latest node-sass/LibSass libraries. Can you please open the bug on their repos?
