### ISSUE TITLE
Escape character (masking quotes) is passed to the compiler output. Compiling foundation scss failed

### ISSUE THREAD

**Issue by thomas-nommensen** [madskristensen/WebCompiler#225]
### Installed product versions
- Visual Studio:2015 community
- This extension: 1.1.32

### Description
Masking Quotes is not decoded. In Foundation framework constructs like \' are used in the scss. Former versions of WebCompiler worked fine with this. Now the \' is passed to the css.

Example:  
@each $type in $types {
    $return: append($return, unquote('[type=\'#{$type}\']'), comma);
  }
now produces something like: [type=\'text\'] 
but should be: [type='text']

**Comment by madskristensen** [comment]
This is a bug in libsass and should be reported on their repo
