### ISSUE TITLE
How to configure CoffeeLint?

### ISSUE THREAD

**Issue by piggest1** [madskristensen/WebCompiler#228]
### Installed product versions
- Visual Studio Community 2015 
- WebCompiler: 1.11.315

### Description
How to config CoffeeLint?

Its a good idea, but with the new CoffeeLint support I got hundreds of errors. Most are: I have indentation 4, but Lint wants 2; and many many Lines ends with whitespaces. 
How can I say Lint my indentation? And is there a kind to repair the spaces at line ends?

**Comment by madskristensen** [comment]
Web Compiler doesn't do anything with CoffeeLint at all. You should change the CoffeeLint settings under **Tools -> Web Code Analysis -> Edit CoffeeLint Settings...**

**Comment by piggest1** [comment]
Thank you very much. You do a good job :)
    
    
    Am 22.05.2016 um 21:39 schrieb Mads
      Kristensen:
    
    
      Web Compiler doesn't do anything with CoffeeLint at all. You
        should change the CoffeeLint settings under Tools ->
          Web Code Analysis -> Edit CoffeeLint Settings...
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub
