### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by jagdipa** [madskristensen/WebCompiler#23]
This looks like an excellent extension. Is there any chance it can be enabled for Visual Studio 2013?

**Comment by GProulx** [comment]
Hi!

On Visual Studio 2013 you can use WebEssentials 2013 that includes all the compiler options of WebCompiler and a lot more!

* You can download it from [VisualStudioGallery](https://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361)
* Documentation about [Less](http://vswebessentials.com/features/less) and [CoffeeScript ](http://vswebessentials.com/features/coffeescript). Scss is also supported by WE2013.

If you have specific questions about Web Essentials 2013, just ask them [on the GitHub repository of the extension](https://github.com/madskristensen/WebEssentials2013/issues)

**Comment by jagdipa** [comment]
A colleague of my has had some bad experiences with WebEssentials - and this looks like a more focuses extension - we only need SASS compilation with CI. Hence the reason for looking for something else.

**Comment by madskristensen** [comment]
This extension uses features only supported in VS2015. For VS2013 you can try SassyStudio if you just need Sass compilation
