### ISSUE TITLE
WebCompiler is disabled after restarting Visual Studio

### ISSUE THREAD

**Issue by michaelvolz** [madskristensen/WebCompiler#233]
### Installed product versions
- Visual Studio: 2015 Professional, DotNet Core Preview 1

### Description
The webcompiler extension is always disabled after restarting visual studio.

Is it possible that the preview 1 tools are doing this?

**Comment by madskristensen** [comment]
This is not related to this extension, but is an issue in VS. You can use [this](https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd) to clear the MEF cache

**Comment by michaelvolz** [comment]
Thank you for the fast feedback, but I am afraid it did not change the problem. Still, every time I close and reopen Visual Studio ONLY the WebCompiler is disabled. I like the extension very much. It makes working with SCSS and ES6 very, very fast and easy. 

Any other suggestions?

**Comment by madskristensen** [comment]
Can you try uninstalling it, restart VS and install it again?

**Comment by michaelvolz** [comment]
Yes of course. I will give it a try after the weekend, when I am back @work and report afterwards.

**Comment by michaelvolz** [comment]
I had to uninstall the extension 3 times, before it really disappeared from Visual Studio. I installed the latest version 315 and everything looks fine now. Thank you very much for your support. 
I am a big fan and I love the work you do.
