### ISSUE TITLE
How to enable "show preview window"

### ISSUE THREAD

**Issue by vortaxg** [madskristensen/WebCompiler#236]
### Installed product versions
- Visual Studio: [2015 Professional SP 2]
- This extension: [1.11.315]

### Description
How to enable "show preview window" like
http://vswebessentials.com/features/less#

### Current behavior
We can't see CSS and it generated LESS file in split windows

### Expected behavior
We have to  see CSS and it generated LESS file in split windows, like
http://vswebessentials.com/features/less#

**Comment by madskristensen** [comment]
The Preview Window is not implemented yet but is on the backlog here #5
