### ISSUE TITLE
TFS access denied on project rebuild

### ISSUE THREAD

**Issue by jerone** [madskristensen/WebCompiler#240]
### Installed product versions
- Visual Studio Professional 2015 Update 3
- This extension: 1.11.315

### Description
Error about access denied path files show up in the error list when rebuilding project with Sass files (haven't tested Less).
Building succeed, only _rebuilding_ doesn't.

### Steps to recreate
1. Check out project from TFS with Sass files.
2. Rebuild the project.

### Current behavior
Error about access denied path files show up in the error list.

### Expected behavior
No errors, and altered files (when there were actual changes).

**Comment by madskristensen** [comment]
Do you have the latest NuGet package?

**Comment by jerone** [comment]
[**@madskristensen**](https://github.com/madskristensen) commented on [30 jun. 2016 18:08 CEST](https://github.com/madskristensen/WebCompiler/issues/240#issuecomment-229707215 "2016-06-30T16:08:22Z - Replied by Github Reply Comments"):
> Do you have the latest NuGet package?

`BuildWebCompiler.1.10.303` is installed in the package folder.

BTW, I'm running the CI build.

**Comment by jerone** [comment]
This seems to be fixed by updating the NuGet package to `BuildWebCompiler.1.11.315`.
