### ISSUE TITLE
Add possibilitty to remove all comments from css file / min file

### ISSUE THREAD

**Issue by msmolka** [madskristensen/WebCompiler#245]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.35]

### Description
Currently comments are generated even in min file. There is alot of empty space as well. I would be good to remove that,

**Comment by duncansmart** [comment]
Use `"commentMode": "none"` in your compilerconfig.json, e.g.

      {
        "inputFile": "Content/foo.less",
        "outputFile": "Content/foo.css",
        "minify": {
          "commentMode": "none"
        }
      }

**Comment by madskristensen** [comment]
Thanks for the explanation @duncansmart. Closing issue
