### ISSUE TITLE
WebCompiler + BundlerMinifier sequence of execution is undefined

### ISSUE THREAD

**Issue by uffefl** [madskristensen/WebCompiler#249]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.11.315

### Description
When using your WebCompiler in conjunction with your BundlerMinifier the sequence of execution of compilation versus bundling and minification is not guaranteed. Case in point my current project runs the bundler before the compiler, which invalidates the bundled files.

It is very easy to fix, which I have done locally in packages\BuildWebCompiler.1.11.315\build\BuildWebCompiler.targets which is liable to get lost during nuget restores etc. (Also I really don't want to add anything from packages\ to version control.)

Simply add a `BeforeTargets="BundleMinify"` to the `<Target Name="WebCompile">` element. MSBuild does not complain if the BeforeTargets target does not exist, so it will simply pass silently by if the bundler isn't installed.

### Steps to recreate
1. Create project with both WebCompiler and BundlerMinifier
2. Setup some bundles depending on some output from the WebCompiler
3. Build once
4. Change something in one of the sources for the WebCompiler
5. Build again

### Current behavior
The changes from item 4 is not included in the bundles, since the BundlerMinifier runs before WebCompiler. Some times. Most of the times. Enough times to be a problem. (I think basically the behavior is undefined...)

### Expected behavior
Any build should bring our targets to the same state. Having to run two builds to make sure nothing got missed would be a shame. Specifically it should be running the WebCompiler before the BundlerMinifier, when both extensions are present.

**Comment by madskristensen** [comment]
Thanks for providing the solution!! I've made the change and if you update the *BuildWebCompiler* NuGet package to version 1.11.320 you should see the changes. Can you please confirm that it works?

**Comment by uffefl** [comment]
Excellent! I won't be able to test it in my production environment until I get back at work on monday, but I'll update here when I do :)

**Comment by uffefl** [comment]
Confirmed: this change works for me.
