### ISSUE TITLE
Less strictMath option doesn't seem to work

### ISSUE THREAD

**Issue by craigktreasure** [madskristensen/WebCompiler#25]
I have the strictMath option set to true, but my css is still coming out wrong. Using 1.0.64 and i don't get any errors when saving either the less or the config files.

compilerconfig.json
```
[
    {
        "includeInProject": true,
        "inputFile": "file.less",
        "minify": {
            "enabled": true
        },
        "options": {
            "strictMath": true
        },
        "outputFile": "file.css"
    }
]
```

file.less
```
...
.class-name {
    height: calc(85% - 60px);
}
...
```

file.css - actual
```
...
.class-name {
    height: calc(25%);
}
...
```

file.css - expected
```
...
.class-name {
    height: calc(85% - 60px);
}
...
```

**Comment by craigktreasure** [comment]
@madskristensen Found the bug. Seems to be in LessOptions.cs line 9 where the value of the configuration is compared to "true" as a string instead of a boolean. Replacing `strictMath: true` with `strictMath: "true"` in the config file works.

Line 9 of LessOptions.cs:
```
StrictMath = GetValue(config, "strictMath") == "true";
```

I won't have time to attempt a fix and submit a PR until later tonight, but am happy to take a wack at it later tonight if you'd like me to.

**Comment by madskristensen** [comment]
Thanks for researching it. Other options might also be affected by the same bug. A PR would be awesome Sine I'm on vacation.

**Comment by madskristensen** [comment]
This was fixed by the pull request and can be closed, right?

**Comment by craigktreasure** [comment]
Correct.
