### ISSUE TITLE
Detached ruleset syntax detected as invalid

### ISSUE THREAD

**Issue by clarkd** [madskristensen/WebCompiler#258]
When using the detached rulesets feature as described [here](http://lesscss.org/features/#detached-rulesets-feature), in particular passing a ruleset as a parameter to a mixin, Visual Studio 2015 shows the code as syntactically invalid.

Does anyone know if support for this has been added in any version of the Web Compiler / Essentials?

**Comment by madskristensen** [comment]
It's a bug in the LESS/Sass editor in VS. It's supported by the compiler in this extension though

**Comment by clarkd** [comment]
Thanks, that's good to hear :)
