### ISSUE TITLE
Variable interpolation in @each incorrectly shows Intellisense error in edge case

### ISSUE THREAD

**Issue by slathrop** [madskristensen/WebCompiler#265]
### Installed product versions
- Visual Studio 2015 Community Update 3
- Web Compiler 1.11.319

### Description
Variable interpolation in @each incorrectly shows Intellisense error in edge case

### Steps to recreate
This example correctly does *not* show an Intellisense error:

    @each $size in (xs, sm, md, lg) {
        .col-#{$size}-pull-1 {
            right: 8.33333333%;
        }
    }

But this example *incorrectly* shows an Intellisense error about the selector .col-#{size}-1 ("Expected a selector for the style rule"):

    @each $size in (xs, sm, md, lg) {
        .col-#{$size}-1 {
            width: 8.33333333%;
        }
    }

### Current behavior
The Intellisense parser doesn't seem to like a selector containing a dash and just a digit *after* an interpolated variable. A dash followed by text (as in the "-pull-1" example above) seems to be OK.

### Expected behavior
The Intellisense parser should recognize a selector containing a dash and just a digit *after* an interpolated variable as being valid.

**Comment by madskristensen** [comment]
this is an issue with the editor in Visual Studio and not this extension, which doesn't provide any Intellisense at all.

**Comment by slathrop** [comment]
Ahhh, OK. Thanks!
