### ISSUE TITLE
Add support for Visual Studio 2017

### ISSUE THREAD

**Issue by kingmotley** [madskristensen/WebCompiler#268]
Add support for being installed in Visual Studio 2017 (or maybe just update NuGet package?)

**Comment by kingmotley** [comment]
Extension seems to work fine (I've compiled one file) in Visual Studio 2017 RC if you go to your old extensions folder and find which folder contains WebCompiler, and then copy it to the 2017 directory.  Then you have to go enable it in Extension/Updates.

**Comment by MaxxDelusional** [comment]
@kingmotley You workaround did not work for me. I copied the folder to my VS2017 extensions folder, but the extension does not show up in Extensions/Updates so I cannot enable it.

**Comment by kingmotley** [comment]
Not sure why it isn't appearing for you, but the good news is that it appears that it does indeed work fine in 2017 RC, so it shouldn't take but a few minutes to publish a new NuGet package and it'll be available for everyone.

**Comment by MaxxDelusional** [comment]
I was able to get the extension working by following this guide https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

I submitted a pull request, although, I have never submitted a pull request before, and I am not sure that I did it correctly.

**Comment by madskristensen** [comment]
Done
