### ISSUE TITLE
Empty @media queries generated when compiling less file with (reference) to bootstrap 

### ISSUE THREAD

**Issue by stilren** [madskristensen/WebCompiler#269]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.11.319

### Description
Empty @media queries generated when compiling less file with (reference) to bootstrap 

### Steps to recreate
1. Download bootstrap less files from http://getbootstrap.com/getting-started/#download
2. Create a less file with a reference import to bootstrap.less and use a mixin:
![image](https://cloud.githubusercontent.com/assets/1575527/20520102/c5e2a884-b0a5-11e6-9e37-1515391b7634.png)

3. Compile your less file

### Current behavior
The css file contains many empty @media queries
![image](https://cloud.githubusercontent.com/assets/1575527/20520121/df1e3f98-b0a5-11e6-948f-e311cee0ca30.png)

### Expected behavior
The css file should not contain empty @media queries
`.mybutton {
  padding: 1px 1px;
  font-size: 1px;
  line-height: 1px;
  border-radius: 1px;
}`

**Comment by madskristensen** [comment]
This is an issue with the node-less module and not with this extension. Please open the bug with them

**Comment by stilren** [comment]
Done:

https://github.com/less/less.js/issues/2991
