### ISSUE TITLE
Global config of "includeInProject"

### ISSUE THREAD

**Issue by MattFromGer** [madskristensen/WebCompiler#271]
I have a little feature request: I need the "includeInProject" attribute to be set globally. I want to exclude all .css files from my project. 

Besides, I noticed that every time I compile/add a new file, my additional attributes from the "compilerconfig.json" get overwritten i.e. "includeInProject" attributes are getting removed.

Anybody else experienced this?

**Comment by Strykeforce01** [comment]
We have the same issue, its quite frustrating. I've tried to set it in the default json but everything is removed when you add a file via visual studio.

I've also noticed that sourcemap: false gets added when I choose to remove a file from compilation, it's quite strange, when I re-add the file the attribute is removed from each entry.

**Comment by MarijnStevens** [comment]
I added a lot of files manual (well.. sublime text and regex) and this extension decide all on it own to just get rid of all these "includeInProject": false lines... and compiles+adds the file to the project again. 

Tried to fix it myself but I don't thing we would agree on where in the code this should be;
