### ISSUE TITLE
Appears in VS2013 NuGet library as available package but doesn't work

### ISSUE THREAD

**Issue by CodeChief** [madskristensen/WebCompiler#28]
I know this works with VS2015 RC so when I saw it was available for 2013 Update 4 I immediately downloaded it. However there are no right-menus or or sign of functionality.

So what does this mean? Did you or Microsoft accidentally flag it as available for 2013 or is 2013 now supported (then how do I get it to work)?

**Comment by CodeChief** [comment]
I can workaround the issue by manually adding a compilerconfig.json to the root of the project, then for example this content to compile Boostrap LESS source (probably one of the most popular uses for this I can see):

[
  {
    "outputFile": "Content/bootstrap.css",
    "inputFile": "Content/bootstrap/bootstrap.less",
    "minify": {
      "enabled": true
    },
    "includeInProject": true,
    "sourceMap": false,
    "options": {}
  },
  {
    "outputFile": "Content/bootstrap-theme.css",
    "inputFile": "Content/bootstrap/theme.less",
    "minify": {
      "enabled": true
    },
    "includeInProject": true,
    "sourceMap": false,
    "options": {}
  }
]

Hope that helps others. Anyway please fix the right-click. Can you please confirm the project IDs your extension supports then I can double-check the GUIDs.

**Comment by madskristensen** [comment]
A NuGet package is not a VS extension - those are two very different concept. The extension doesn't work on VS2013 and never will. The NuGet package is being used by the extension but shouldn't be used in its own.
