### ISSUE TITLE
LESS compiler w/ StrictMath breaks negative numbers

### ISSUE THREAD

**Issue by BrandonLive** [madskristensen/WebCompiler#29]
I don't see this problem with my Grunt task that runs at build-time (also using StrictMath), only with compile-on-save via Web Compiler (which I use to enable BrowserLink to do its thing when I CTRL+S).

Problem is that this in my .less file:
top: -100px
becomes this in the CSS:
top: - 100px

This is invalid CSS and isn't accepted by browsers.

**Comment by madskristensen** [comment]
Fixed
