### ISSUE TITLE
Crashing on compile

### ISSUE THREAD

**Issue by scottdorman** [madskristensen/WebCompiler#3]
The extension was working fine. I made some minor changes to some of the files (moved some content around, removed a file, renamed another file) and added `@import (reference) ...` lines to the top of some of the files and now the extension crashes every time it tries to compile. It turns out, I missed updating an import statement in my main .less file, so the compiler was failing with a file not found error, but that was causing the extension to crash Visual Studio.

**Comment by madskristensen** [comment]
Yikes. A fix  is coming asap

**Comment by madskristensen** [comment]
Version 1.0.10 is now released to the Gallery with the fix
