### ISSUE TITLE
Less compiler version ?

### ISSUE THREAD

**Issue by lamenagere** [madskristensen/WebCompiler#30]
Hi,
Would it be possible to update the LESS compiler ? It seems it's still in LESS version 1.5.0.
That would be great because it introduces a lot of new enhancements!
Thx,
Nico.

PS: I would also thank you for your amazing work on web essentials & compiler. I do understand your choices. Bravo!

**Comment by GProulx** [comment]
Hi,

You're right that WebCompiler uses [dotless 1.5.0](https://github.com/madskristensen/WebCompiler/blob/master/src/WebCompiler/WebCompiler.csproj#L47). But this seem to be the [newest available release on GitHub : https://github.com/dotless/dotless/releases?

**Comment by lamenagere** [comment]
Unfortunately, you're right. It seems that the guy is alone on his project. I really hope that he will follow the evolution of LESS though and keep it up to date...

**Comment by madskristensen** [comment]
What are the alternatives to dotless if I don't want to rely on node.js?

**Comment by madskristensen** [comment]
Lauri is still working on dotless and a new version is coming shortly he told me today. LESS 2.0 is also on the roadmap

**Comment by kingmotley** [comment]
Mads, if you don't want to use node.js, can't you use use one of the javascript engines directly to invoke less.js?
