### ISSUE TITLE
"includeInProject": false is deleted from config file

### ISSUE THREAD

**Issue by BernhardJ** [madskristensen/WebCompiler#315]
### Installed product versions
- Visual Studio 2015 / 2017 Enterprise
- This extension: 1.11.326

### Description
If I add a new scss file, the compilerconfig.json is written, but the existing settings "includeInProject": false are deleted.

### Steps to recreate
1. In the Solution Explorer select a file, which is not listed in the compilerconfig.json file
2. Open the context menu -> Web Compiler -> Compile file 
3. The file is added to the compilerconfig.json file
4. All "includeInProject": false from the other files are deleted

### Current behavior
The settings from the other files should not be touched

### Expected behavior
All existing settings should be left in the file

**Comment by MattFromGer** [comment]
Same issue as [https://github.com/madskristensen/WebCompiler/issues/271](url)

**Comment by BernhardJ** [comment]
Thanks
