### ISSUE TITLE
[Q][SASS] How I can tell WC to remove comments from generated CSS file?

### ISSUE THREAD

**Issue by dehghani-mehdi** [madskristensen/WebCompiler#318]
Hello,

### Installed product versions
- Visual Studio: 2017 Enterprice
- This extension: 1.11.347

### Description
How I can tell WebCompiler to remove comments from generated CSS file? (actually is there any flag that can set to `compilerconfig.json` or `compilerconfig.json.defaults`?)

Thanks.

**Comment by emptyother** [comment]
No idea about SASS, but in the LESS compiler the line comments/double slashes gets removed. Block comments /* */ is kept. 

Source: https://github.com/madskristensen/WebCompiler/issues/318

**Comment by dehghani-mehdi** [comment]
R.I.P
