### ISSUE TITLE
Disable "use-strict" on ES5 compile?

### ISSUE THREAD

**Issue by DinsmoreDesign** [madskristensen/WebCompiler#332]
### Installed product versions
- Visual Studio: Enterprise 2017
- This extension: 1.11.326

### Description
I know it's possible with Babel to disable "use-strict" when compiling to ES5, but I haven't found a solution with Web Compiler... While I'd prefer to use a Web Pack build process that I can fully control, the project I'm working on has multiple developers working on it, most of which have never worked with NPM before and using Web Compiler is just a far more easy process. The addition of use-strict breaks some of our code on older browsers.

### Steps to recreate
1. Create ES6 JS file
2. Right click, select Web Compiler
3. Select Compile/Re-Compile
4. Check compiled ES5 code and "use-strict" is included at the top

### Current behavior
Adds "use-strict" at top of compiled ES5 JS file.

### Expected behavior
Option in compilerconfig.json would allow us to omit adding "use-strict" to the files.

**Comment by PVLopes** [comment]
> Option in compilerconfig.json would allow us to omit adding "use-strict" to the files.

I would like this option too.
Does WebCompiler support this?
Does anyone have a quick solution?
