### ISSUE TITLE
VS2017 15.4.1 upgrade 

### ISSUE THREAD

**Issue by wgrs** [madskristensen/WebCompiler#339]
### Installed product versions
- Visual Studio: 2017 15.4.1
- This extension: [example 1.5.31]

### Description
When upgrade to VS was applied, all web essential tools disappeared from menus and functionality stopped working

### Steps to recreate
1. Install 15.4.1 upgrade
2. Try to compile scss file

### Current behavior
Web Essentials not available on menus

### Expected behavior
Web Essentials working as in previous version of VS

**Comment by rthavi** [comment]
FYI I was having this same issue and solved my problem.  The short answer:  there were WebCompiled files hidden in the solution.  Check and see if any of the files you _expect_ to be compiled aren't, in fact, excluded from the project view.

I had recently got a new computer at work and did clean installs of my entire environment, including upgrading to VS 2017.  I connected to my Bitbucket repo and made a new branch of the project I'm working on.

The LESS file I was trying to compile for some reason wasn't showing the minified/compiled file (custom.less => custom.min.css) file in the solution itself (though it was still in the project folder).  I was simply going to compile the LESS in another tool and copy-paste it into a new file called "custom.min.css" to avoid modifying BundleConfig.  When I tried to make the new css file, VS threw a warning that the file already existed...so I added an existing item to the solution...lo and behold it was in the project folder already.  When I added it, the WebCompiler option showed up in the right-click context menu, and compilerconfig.json magically reappeared in the project too.

Hope this helps someone!
