### ISSUE TITLE
Please release version 1.11.375 to the market place

### ISSUE THREAD

**Issue by ThomasZitzler** [madskristensen/WebCompiler#346]
### Installed product versions
- Visual Studio: 2017.5.4 Enterprise
- This extension: 1.11.326

### Description
I installed the latest nuget package for the webcompiler msbuild integration (WebCompiler1.11.375) and now the files generated during "save" are slightly different than the ones generated by the msbuild.

The case we have is that we have set the map files to be included in the css as base64 and the "old" version generates an additional "file: undefined" entry at the end of the source map.

This causes some confusion and since we check in the css files to git, it also causes not so nice changes in the version history.

Please release an official version of the 1.11.375 extension to the marketplace so that we can use the same versions.

**Comment by John0King** [comment]
Please release the new version
