### ISSUE TITLE
Add support for autoprefixer

### ISSUE THREAD

**Issue by kingmotley** [madskristensen/WebCompiler#35]
It would be nice if autoprefixing was an option like it was in WE 2013.

**Comment by GProulx** [comment]
This request was already discussed on #4

**Comment by kingmotley** [comment]
What about using https://github.com/digitalcreations/autoprefixer?

**Comment by madskristensen** [comment]
Duplicate of #4

**Comment by madskristensen** [comment]
Duplidate of #4

**Comment by madskristensen** [comment]
I found a plugin to the LESS compiler, so this is doable. Adding it now
