### ISSUE TITLE
Nothing compiled... Missing steps in "Getting started"?

### ISSUE THREAD

**Issue by smukkekim** [madskristensen/WebCompiler#36]
Hi!
I installed the extension. Right clicked and chose "Compile file" on all my less-files.
They were all added to the compilerconfig.json in project root, as described.
But nothing gets compiled. 
* Editiing and saving one of the less files does nothing. 
* Right-clicking compilerconfig.json and choosing "Re-compile all files" does nothing.

css-files are not updated and no error messages pop up anywhere.

Is there some pre-requisite not mentioned in the "Getting started"-section?

**Comment by AdamDotNet** [comment]
I thought this too, but I actually had errors, which weren't even errors in VS 2013. Check the Error List window.

For me, I was doing font with line height in one CSS attribute

```css
font: @default-input-font-size/@default-input-line-height @default-font-family;
```

The error produced is, variable `@default-input-font-size` is undefined. Clearly that is incorrect.

But to get the new Less compiler to work, I had to change it to this, removing the / character and making separate declarations. That's kind of disappointing.

```css
font: @default-input-font-size @default-font-family;
line-height: @default-input-line-height;
```

**Comment by smukkekim** [comment]
Ok. But as I said. There are no errors. The error list window is empty.

**Comment by smukkekim** [comment]
Ok. Solved it... 
I have no idea why nothing happened, but after uninstalling/reinstalling the extension (twice), and deleting and recreating the *compilerconfig.json*, it started compiling files.
