### ISSUE TITLE
Error "No such file or directory" after "install updated versions of compiler" with  .Net Core 2.1.4

### ISSUE THREAD

**Issue by SaschaJohn** [madskristensen/WebCompiler#364]
### Installed product versions
- Ubuntu Ubuntu 17.10 with .Net Core 2.1.4
- This extension: 1.11.375

### Description
Build in Windows works without any issues, so project seem to be correct.
When building in Linux, we get an error "no such file or directory" after
"Webcompiler installing updated versions of the compilers..."

### Steps to recreate
Start Build
![2018-02-28 14_48_45-mremoteng - confcons xml - ubuntubitbucket](https://user-images.githubusercontent.com/220592/37757119-22311c2c-2dac-11e8-8ec3-54a11b40b375.png)

### Current behavior
Build fails

### Expected behavior
Build succeeds

**Comment by fr0zenbits** [comment]
I'm having the same issue

**Comment by enhendrickson** [comment]
@SaschaJohn did you ever figure this out? I am seeing this same symptom.

**Comment by SaschaJohn** [comment]
@enhendrickson this project currently only supports Windows. All compiler invocation is done via cmd files

**Comment by Banner-Keith** [comment]
I am also having this issue. Until this is resolved I will have to move to a different solution with gulp or webpack.

**Comment by SaschaJohn** [comment]
@Banner-Keith can you suggest somewhat?

**Comment by mbp** [comment]
We have the same problem. It's not possible to build ASP.NET Core application with the dotnet Docker images.

I also wonder what other are using as alternative to WebCompiler?

**Comment by jacqueskang** [comment]
I'm having the same issue

**Comment by Banner-Keith** [comment]
I am now using webpack. It works well but is more work to implement than webcompiler. Ultimately I won't go back as once webpack is implemented there's no reason to go back.

**Comment by qJake** [comment]
Does this project support Linux yet (nearly a year later)?

**Comment by andre-dasilva** [comment]
Are there any plans to support Linux? I installed webcompiler and i still get this error

**Comment by dedmen** [comment]
And just fell into this too.
I think I'll just replace it with manually calling the sass compiler for every file in my CI.

**Comment by KrzysFR** [comment]
Same issue here, looking at the code in `CompilerService.Initialize()` it seems that it is Windows only: it checks for the presence of `node.exe`, and if missing, wants to run a `prepare.cmd` script by invoking `cmd.exe`...

https://github.com/madskristensen/WebCompiler/blob/586295ba3c3107b7613dcb5a02667aad817045d4/src/WebCompiler/Compile/CompilerService.cs#L78-L118

It wants to find `node_modules`, `node.exe` and `log.txt` inside the `_path` folder, but this folder is created from a temporary path (line 14 in same file), so I don't think it's possible to pre-create the files and trick it into not running prepare.cmd ?

Only workaround I see, is to create fake 'cmd.exe' bash script, in the PATH, that would emulate what the prepare.cmd attempts to do ? https://github.com/madskristensen/WebCompiler/blob/586295ba3c3107b7613dcb5a02667aad817045d4/src/WebCompiler/Node/prepare.cmd#L1-L9

**Comment by Vertigo093i** [comment]
Why? Why it is still Windows-only?

**Comment by Ryangr0** [comment]
Still the exact same issue two years later. Bizarre. How are people doing this?
