### ISSUE TITLE
 "WebCompile" is not run

### ISSUE THREAD

**Issue by hasan9th** [madskristensen/WebCompiler#383]
### Installed product versions
- Visual Studio: Visual Studio 2015
- This extension: Web Compiler v1.11.384

### Description
Today I unexpectedly encountered an error. I think it should be related to the new system update. I would highly appreciate your kind assistance about it. Please find attached a screen shot of the error and should you need any further information, please just let me know.

### Current behavior
Target "WebCompile" is not run, and throw error "Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. the system cannot find the file specified.
"
![1](https://user-images.githubusercontent.com/30544201/46259255-f2819900-c4e3-11e8-9768-887194c38056.PNG)

### Expected behavior
Target "WebCompile" is run and Css files are generated.

**Comment by bignol** [comment]
+1 I am also receiving this error as of today in the same environment.

**Comment by wvandeneede** [comment]
Hi,

Since today we are experiencing the same issue on some of our machines.

Visual Studio 2015
Web Compiler v1.11.384

Uninstalling and re-installing the extension doesn't result in a fix.
Found this workaround/question on stack-overflow: https://stackoverflow.com/questions/52583164/visual-studio-newtonsoft-json-error-when-running-webpack

**Comment by madskristensen** [comment]
I know what the issue is and I'm working on fix right now

**Comment by madskristensen** [comment]
Please try the CI build to see if it fixed the issue http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by wvandeneede** [comment]
@madskristensen, we tested with 1.12.387 and it seems to be working, compiling takes a bit of time but in the end the css is generated ok.
