### ISSUE TITLE
SyntaxError: Inline JavaScript is not enabled.

### ISSUE THREAD

**Issue by cannontrodder** [madskristensen/WebCompiler#384]
### Installed product versions
- Visual Studio 2017
- Web Compiler version 1.11.384

### Description
Once of our devs updated to the latest version of web compiler inadvertently but then found he and only he got the error "SyntaxError: Inline JavaScript is not enabled." in a less file that pulls in lesshat (which I understand had inline javascript)

It looks like the less loader configuration changed the default for running line JavaScript https://stackoverflow.com/questions/46729091/enable-inline-javascript-in-less

We're trying to find a cached version of the web compiler to help us out but is there a way for us to override this setting (the loader setting)?

**Comment by madskristensen** [comment]
Do you know what the CLI setting is for enabling JavaScript? Here are the options set by Web Compiler https://github.com/madskristensen/WebCompiler/blob/master/src/WebCompiler/Compile/LessCompiler.cs#L109

**Comment by cannontrodder** [comment]
I think it is '--js' : http://lesscss.org/usage/#command-line-usage

On that page it says

```
lessc --js | { javascriptEnabled: true }
```
