### ISSUE TITLE
Error loading LESS plugin "no-ie-compat"

### ISSUE THREAD

**Issue by jlao** [madskristensen/WebCompiler#386]
### Installed product versions
- Visual Studio: 2017 Enterprise (15.8.5)
- This extension: 1.12.389

### Description
Getting this error when trying to compile LESS:
Unable to load plugin no-ie-compat please make sure that it is installed under or at the same level as less

### Steps to recreate
Not sure. I opened a project with an existing LESS file that was valid and I cannot compile it. I noticed that this extension was recently updated so I'm wondering if there was a regression?

### Current behavior
An existing LESS file that is valid no longer compiles.

### Expected behavior
The LESS file should compile.

**Comment by jordan-playfab** [comment]
In the meantime, one workaround is to go to compilerconfig.json.defaults (under compilerconfig.json) and change the "less" > "ieCompat" value to true. The CSS generated may change, but it'll compile.

**Comment by jlao** [comment]
The issue has been fixed in the new version (1.12.394).
