### ISSUE TITLE
Compiling no longer functions

### ISSUE THREAD

**Issue by bkmak** [madskristensen/WebCompiler#399]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.9.2
- This extension: 1.12.394

### Description
Attempting to compile an SCSS file results in this popup error message: "There is an error in the compilerconfig.json file. This could be due to a change in the format after this extension was updated."

### Steps to recreate
1. Add SCSS file to project.
2. Right-click SCSS file > Web Compiler > Re-compile file.

### Current behavior
When the popup error message appears, there is a message on the bottom of Visual Studio that says "Installing updated versions of the web compilers...".

The Output window shows this message: "Error loading schema http://json.schemastore.org/compilerdefaults-schema.json"

Navigating to http://json.schemastore.org/compilerdefaults-schema.json in a browser shows this message: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

### Expected behavior
Compiling should complete successfully, which it was doing as recently as last week. I have not edited the SCSS file, the compilerconfig.json file, nor the WebCompiler extension since that time.

**Comment by PlanetPayDave** [comment]
Hello, I am getting exactly the same behaviour.  Have been able to resolve the problem?

**Comment by MaiSaan** [comment]
I get the same error message... however my schema is http://json.schemastore.org/compilerconfig im at a loss here. My project is on hold because i cannot compile my sass files..

**Comment by adaptabi** [comment]
same error here. How to fix it?

**Comment by MaiSaan** [comment]
> same error here. How to fix it?

Hey man, try this, https://stackoverflow.com/questions/39287333/web-compiler-compile-on-save-not-working

it worked for me, i had to do it a few times, restart a few times, reinstall a few times, no idea what fixed it but in the end it is working fine for me now.

this happened to me once before as well, that time i deleted the temp files, unistalled webcompiler and downgraded to an older version Web Compiler v1.11.326. 

Hope this helped.

**Comment by dehghani-mehdi** [comment]
See this question on SO-> [How do I solve 'Web Compiler found an error in compilerconfig.json'](https://stackoverflow.com/a/47166403/3367974)
