### ISSUE TITLE
Add support for Autoprefixer

### ISSUE THREAD

**Issue by scottdorman** [madskristensen/WebCompiler#4]
Add support for [Autoprefixer](https://github.com/postcss/autoprefixer) to deal with [CSS vendor prefixes](http://webdesign.about.com/od/css/a/css-vendor-prefixes.htm) (or give us a way we can hook it into the compilation process ourselves.)

**Comment by madskristensen** [comment]
Is there a .NET component that can do this? Writing one using CSS editor components in VS wouldn't be that hard, but would take time.

**Comment by scottdorman** [comment]
I don't know if there is a .NET component for this or not, I don't think there is. If you're using gulp under the hood to compile the CSS, there is a gulp task that could be used. I think it would have to come into play as a "post-compile" step since it would have to update the generated CSS. Alternatively, if you are using gulp under the hood, some extensions to the compilerconfig.json file to let us add/configure our own gulp tasks would be nice - that gets you out of having to support multiple post-processors in the future. (I say that, but I don't know how hard it would be to open up the json file like that.)

**Comment by madskristensen** [comment]
I'm not using node.js in any way in this extension. That's what made the implementation so unstable in Web Essentials 2013

**Comment by madskristensen** [comment]
For any chaining/piping of processors, gulp should be used. It's beyond the scope of this extension. Closing

**Comment by madskristensen** [comment]
Autoprefixer for the LESS compiler has now been implemented. The Sass compiler doesn't support it unfortunately.
