### ISSUE TITLE
Support for F12

### ISSUE THREAD

**Issue by nimeshdhruve** [madskristensen/WebCompiler#40]
It was great to jump to less file just by pressing F12 inside the cshtml file against class name, please add that to Web Compiler.

**Comment by madskristensen** [comment]
That feature should still be in Web Essentials 2015. It doesn't use the compiler to do that at all

**Comment by nimeshdhruve** [comment]
Thanks Mads, since I don't use any of the features from Web Essentials I didn't install Web Essentials and was just having WebCompiler, after I installed WebEssentials I was able to jump to definition using F12.
