### ISSUE TITLE
Compiling SCSS crashes VS2019 Review

### ISSUE THREAD

**Issue by datvm** [madskristensen/WebCompiler#400]
### Installed product versions
- Visual Studio: Visual Studio 2019 (16.0.0)
- This extension: 1.12.394

### Description
VS2019 crashes whenever it tries to compile SCSS file.

### Steps to recreate
1. Install Web Compiler on VS 2019 Preview.
2. Create a SCSS file, for example `foo.scss`.
3. Choose Compile command, or, after the crash, come back to VS2019, change something to SCSS file and click Save.
4. VS 2019 Preview crashes and tries to restart itself. `foo.css` is created with empty content.

### Current behavior
VS 2019 Preview crashes and tries to restart itself. `foo.css` is created with empty content.

### Expected behavior
`foo.css` and `foo.min.css` should be created.

**Comment by datvm** [comment]
I have found 2 workarounds for now:

* If you have VS 2017 with Web Compiler, simply use it there for the first time. It will works when you come back to VS2019.

* If you don't want to go to VS2017, create the files manually, for example: test.scss, test.css and test.min.css. Then use Web Compiler's Compile command. It will crash and VS2019 will restart itself. Next time you change something and save the scss file, the css and min.css files are updated.

The VS team is also investigating: https://developercommunity.visualstudio.com/content/problem/402325/web-compiler-crashes-on-vs2019.html

**Comment by mbarmettler** [comment]
long time since then - but have you also expirinced this with LESS?
