### ISSUE TITLE
The WebCompilerproject doesn't build - missing node_modules.7z

### ISSUE THREAD

**Issue by mhenry1384** [madskristensen/WebCompiler#412]
### Installed product versions
- Visual Studio: 2017

### Description
Try to build the the project "WebCompiler".

 CSC : error CS1566: Error reading resource 'WebCompiler.Node.node_modules.7z

WebCompiler\src\WebCompiler\Node\node_modules.7z is in the .csproj, but it is not checked in.  node.7z, in the same folder, *IS* checked in so it would seem node_modules.7z was excluded accidentally.

**Comment by mhenry1384** [comment]
Oh, I get it.  You have to run build.cmd.

**Comment by RobotOptimist** [comment]
I just cloned this project and I'm having this issue. Can you please elaborate on the steps you took to resolve this @mhenry1384 ?

**Comment by RobotOptimist** [comment]
@mhenry1384 just read your readme and that has it, thank you! 
https://github.com/mhenry1384/WebCompiler
