### ISSUE TITLE
Group source and compiled files in VS file list

### ISSUE THREAD

**Issue by rodrigopires** [madskristensen/WebCompiler#42]
Why files are not grouped anymore, like they were on WE 2013? Is there some configuration we can do to achieve it?

Before:

![Before]
(http://i.imgur.com/eZDbkq6.jpg)

Now:

![Now]
(http://i.imgur.com/QXb7QD2.jpg)

**Comment by madskristensen** [comment]
Use the File Nesting extension for that https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c

**Comment by rodrigopires** [comment]
Thanks @madskristensen  :wink:
