### ISSUE TITLE
xdg-open unexpected argument '/c' in VSCode on Linux

### ISSUE THREAD

**Issue by spaasis** [madskristensen/WebCompiler#421]
### Installed product versions
- Visual Studio: VSCode
- This extension: 1.12.394

### Description
When opening a solution with this BuildWebCompiler  installed in VSCode on Linux, the following error is thrown when Omnisharp loads: `xdg-open unexpected argument '/c'`. I originally thought this was an error in Omnisharp, but if I uninstall this nuget package and reload, the build works correctly.

The original issue: https://github.com/OmniSharp/omnisharp-vscode/issues/3060 

Is WebCompiler even supposed to work on VSCode/Linux or is it strictly tied to Visual Studio?

**Comment by spaasis** [comment]
Seems to work fine on Windows, so I guess this is Linux-related?
OS Name: antergos
OS Version:
OS Platform: Linux
RID: arch-x64

**Comment by rmunn** [comment]
There seems to be some code in WebCompiler that assumes it's running on Windows, e.g. https://github.com/madskristensen/WebCompiler/blob/586295ba3c3107b7613dcb5a02667aad817045d4/src/WebCompiler/Compile/CompilerService.cs:

```csharp
                    ProcessStartInfo start = new ProcessStartInfo
                    {
                        WorkingDirectory = _path,
                        CreateNoWindow = true,
                        WindowStyle = ProcessWindowStyle.Hidden,
                        FileName = "cmd.exe",
                        Arguments = "/c prepare.cmd"
                    };
```

It looks like WebCompiler is (currently) not designed to work on Linux.

**Comment by spaasis** [comment]
Right, that seems like the case. I'll close this ticket and put forth a mental +1 for linux support (or at least not crashing on it :) )
