### ISSUE TITLE
Compile File...  default file name

### ISSUE THREAD

**Issue by glittle** [madskristensen/WebCompiler#45]
Clicked on a .less file.

It would be very good if the suggested file name could have the required extension (.css) added by default. Currently it shows the name of the HTML file, and offers to overwrite it if I don't add the extension.

**Comment by madskristensen** [comment]
It does the right thing on my machine. Can you please provide repro steps, since I assume this only happens in some cases and not in others (perhaps most cases).

**Comment by madskristensen** [comment]
@glittle any more details about this would be helpful

**Comment by glittle** [comment]
Sorry Mads... I had to go back to VS 2013 to get work done. Tested again...

Here's what I get when I right-click on the LESS file and add it to compilation, and accept the suggested file name:
![image](https://cloud.githubusercontent.com/assets/85186/8939386/66b3b746-3521-11e5-9142-b50531db19ab.png)

After adding the .css to the file name and saving, I get this:
![image](https://cloud.githubusercontent.com/assets/85186/8939401/7d527ed8-3521-11e5-9b5b-469e6fd26d22.png)

After using a file nesting addin, I end up with the desired layout in the solution explorer:
![image](https://cloud.githubusercontent.com/assets/85186/8939425/8bfdf70a-3521-11e5-9682-ea9abb05174d.png)
