### ISSUE TITLE
Question: implementation as dotnet core global tool

### ISSUE THREAD

**Issue by stefanloerwald** [madskristensen/WebCompiler#453]
Hi,

is there any plan to create a dotnet core global tool version of this? As much as I love having this in my build integrated in VS, it doesn't work inside a docker build process (someone has to first use VS with the extension installed to create the files, then pass that to the docker build process). This isn't exactly suitable for automated pipelines. So I'm just wondering whether it's a lot of effort to make this into a tool?

Happy to help with the project, just let me know.

BR
Stefan

**Comment by mackcoding** [comment]
The developer @madskristensen  gave up on this extension. There hasn't been a bug fix in ages (and it's buggy in VS2019) so I doubt your request will ever get seen.

**Comment by stefanloerwald** [comment]
@mackcoding Seems very much like it.. What a shame... Do you know whether there are proper alternatives out there?

**Comment by ensemblebd** [comment]
node, babel, and webpack I think is the clear winner here.
But I love the ease of this plugin. Agreed, is too bad it's not maintained any longer.

**Comment by stefanloerwald** [comment]
@ensemblebd ugh, non-C# alternatives? I would love to have a pure dotnet core build pipeline. After all, I'm building blazor applications, not nodejs or js-heavy applications.

**Comment by tomasr78** [comment]
Webpack is a total monster and if you can avoid it then avoid in ASP.NET core!

**Comment by ensemblebd** [comment]
totally agree lol :(

**Comment by stefanloerwald** [comment]
I feel like there's demand for a proper continuation of this project. I'll have a look at the code-base and see whether it's worth investing time into developing a dotnet core version of this.

**Comment by stefanloerwald** [comment]
Okay, I've had a quick look now. Seems like the whole project is largely dependent on node and a few packages. Not the easiest dependency to deal with (with the aim being cross-platform support).

**Comment by stefanloerwald** [comment]
I spent my day on the re-write, cutting down on supported languages for the start. It's just scss for now. Here's the repo: https://github.com/excubo-ag/WebCompiler 

Feel free to contribute support for languages!

**Comment by mackcoding** [comment]
> I spent my day on the re-write, cutting down on supported languages for the start. It's just scss for now. Here's the repo: https://github.com/excubo-ag/WebCompiler
> 
> Feel free to contribute support for languages!

Thanks. I'll def follow this project!
