### ISSUE TITLE
Does not work in JavaScript Windows Store projects

### ISSUE THREAD

**Issue by pke** [madskristensen/WebCompiler#46]
Why is that? I would like to use the CoffeeScript compiler also in Windows Store JavaScript projects.

**Comment by madskristensen** [comment]
What exactly doesn't work. How can I repro the issue?

**Comment by madskristensen** [comment]
@pke Can you provide more info, please?

**Comment by pke** [comment]
I am sorry I was on vacation. Thanks for keeping an eye on the issue and reminding me.

It seemed the compiler does only work when the Web Essentials Extension is also installed?
After I figured that out, the coffee files in my WinJS Project compile. However there seems to be a slight problem:

In my project I include a `common.proj` that contains wildcard inclusion like this:
`<None Include="pages\**\*.*coffee" />`
the compiler sometimes saves the compiled file relative to the parent project instead parallel where the coffee files sits. I'll try to build a small repro project for you to test. Meanwhile you could check in which relation the compiled files are saved. They should be in the same path as the .coffee file they belong to.

**Comment by madskristensen** [comment]
Fixed in latest nightly build http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by pke** [comment]
Thanks! I will check it out :)
