### ISSUE TITLE
Error when building in VSO

### ISSUE THREAD

**Issue by mgaring** [madskristensen/WebCompiler#47]
When doing a build in VSO I receive the following error:

d:\a\src\packages\BuildWebCompiler.1.0.73\build\BuildWebCompiler.targets (7): Syntax error in d:\a\src\Dashboard.Web\compilerconfig.json

Here is what is in my complerconfig.json

[
  {
    "outputFile": "Content/Dashboard.css",
    "inputFile": "Content/Dashboard.less",
    "minify": {
      "enabled": true
    },
    "includeInProject": true,
    "sourceMap": false,
    "options": {}
  }
]

I'm using version 1.0.73 of WebCompiler

Thanks,
Matt

**Comment by madskristensen** [comment]
Can you try in the latest version 1.1 and see if this is fixed?

**Comment by mgaring** [comment]
I got the nightly build from 8/2 and tried that one.  I received the same error.

**Comment by madskristensen** [comment]
Did you update the NuGet package as well?

**Comment by mgaring** [comment]
Thanks.  I updated the NuGet package and had one successful build.  On the next build after that one I got the following error:

d:\a\src\packages\BuildWebCompiler.1.1.103\build\BuildWebCompiler.targets (7): Access to the path 'd:\a\src\Dashboard.Web\Content\Dashboard.min.css' is denied

**Comment by fredrikeriksson** [comment]
I'm also getting access denied on my compiled resources if they're checked in and while doing a build.
After I do "Re-compile all files" on the project, which check out all the items, I can now build again.
So it seems the "Compile on Build" feature doesn't have the capability of checking out files?

Visual Studio 2015 Enterprise with Web Compiler 1.2.118

**Comment by mgaring** [comment]
We've had half a dozen successful builds with the latest Nuget package so I'd say its fixed.

Thanks for the help.

**Comment by onionhammer** [comment]
This should be reopened.

**Comment by codecypher** [comment]
I am getting this error with version 1.12.394. Not sure how to fix or work around
