### ISSUE TITLE
Error when saving .less file

### ISSUE THREAD

**Issue by jfren484** [madskristensen/WebCompiler#48]
I have Visual Studio 2015 Enterprise (rtm), and a web application started in VS 2013 (so it's not using new ASP.NET 5 features). I just started trying to use LESS, so I installed Web Essentials 2015 and Web Compiler.

I renamed Site.css to Site.less and added it for compilation (right-click, chose Compile File, told it to save back to the same folder as the .less file).

Now when I save it, I get an error dialog:
![image](https://cloud.githubusercontent.com/assets/3483492/8883361/ce19ac8a-3213-11e5-8c34-f975522f9ad5.png)

The odd thing is that it does re-generate the css file. Also, right-clicking the .less file in solution explorer and choosing "recompile file" works without any error dialog.

Here's my compilerconfig.json file, which I have not modified myself:
```
    [
      {
        "outputFile": "Content/Site.css",
        "inputFile": "Content/Site.less",
        "minify": {
          "enabled": true
        },
        "includeInProject": true,
        "sourceMap": false,
        "options": {}
      }
    ]

**Comment by madskristensen** [comment]
Can you please send your Site.less file to madsk at Microsoft com?

**Comment by madskristensen** [comment]
Also, are you using TFS and is the output file locked by it?

**Comment by madskristensen** [comment]
Never mind, I figured it out. Fix coming asap
