### ISSUE TITLE
Error compiling on build

### ISSUE THREAD

**Issue by CheloXL** [madskristensen/WebCompiler#50]
Hi, I'm getting the following error "Expected '}' but found 'n' on line 272 in file ...\tables.less". The thing is, if I compile that file alone (by modifying it of by selecting "Recompile all files" over the compilerconfig.json) I don't get any errors and the file gets correctly compiled.

That line (272 of table.less) has this code:
```css
animation-name: bounce_loadingProgress;
```

I'm not sure what other information might be useful for you...

**Comment by madskristensen** [comment]
Does the version of the nuget package match the version of the extension?

**Comment by CheloXL** [comment]
Yes, I upgraded both (via nuget). 1.0.75

**Comment by CheloXL** [comment]
Now that i'm double checking, I was wrong. The table.less is not compiling at all (but does not throws any errors when compiling alone).

**Comment by CheloXL** [comment]
More info: Indeed, the problem is on that line. Commenting out that line kicks in the compilation.

**Comment by madskristensen** [comment]
I can repro the issue with the latest 1.5.1-Alpha1 of DotLess. I've opened the bug here https://github.com/dotless/dotless/issues/471
