### ISSUE TITLE
Suggestion: post-processor

### ISSUE THREAD

**Issue by CheloXL** [madskristensen/WebCompiler#51]
Add a way to configure an executable that will run after the compilation has ran. In this way, I can add autoprefixer again (running from node, of course).
Maybe you can add this option to the bundler too (to run between bundling and minification).

**Comment by madskristensen** [comment]
Why not just run Gulp if you're setting up node modules anyway?

**Comment by CheloXL** [comment]
Never used gulp, and I just installed node to run autoprefixer. There is really no need for me to use node for anything. 
And hooking node on the post-build event is not an option, because that runs after the bundling/minification.

**Comment by kingmotley** [comment]
Why aren't you doing bundling and minification in node?

**Comment by CheloXL** [comment]
As I said, because I just installed node to run autoprefixer. I don't use node and I would like not to have to use it, but with autoprefixer removed from webessentials, I had no other choice.

**Comment by madskristensen** [comment]
Duplicate of #35

**Comment by madskristensen** [comment]
Auto prefixer is coming to the LESS compiler. Adding it now
