### ISSUE TITLE
Enable compile on build fails with source control

### ISSUE THREAD

**Issue by danda1man** [madskristensen/WebCompiler#55]
If the css file is not checked out prior to building, the build will fail with access denied to the file.  I am on version 1.0.85

![image](https://cloud.githubusercontent.com/assets/852995/8986176/949329f0-36a0-11e5-8a5e-8f59fc810c41.png)

**Comment by danda1man** [comment]
If this was released (I'm on 1.1.103), the patch did not work.  I think instead of marking the file as not readonly it needs to be checked out of source control.

**Comment by madskristensen** [comment]
Did you update the nuget package?

**Comment by danda1man** [comment]
Yeah, both were on 1.1.103.  Looking at your code change though, you don't use the "Recompile" action which checks out all of the affected files, you are just marking the file as not readonly.

**Comment by madskristensen** [comment]
What code is that exactly? Link?

**Comment by danda1man** [comment]
Your patch that just makes it readonly: https://github.com/madskristensen/WebCompiler/commit/e7b5310943e21b808c730ee9c2a374deeea5b66a
The code for recompile: https://github.com/madskristensen/WebCompiler/blob/master/src/WebCompilerVsix/CompilerService.cs

The Compiler Processor checks out the source map, minified file, everything before compiling.  The build action (first link), just makes removes the readonly flag.

**Comment by madskristensen** [comment]
yeah, but that's because the MSBuild taks doesn't have access to the VS APIs for checking files out of source control. Do you know if that is possible from MSBuild without taking a hard dependency on TFS?

**Comment by danda1man** [comment]
Hmm I see.  I don't now of a way around that.  Is it a big deal adding the dependency since its already there for the VISX?

**Comment by madskristensen** [comment]
yeah, because of the CI server scenario

**Comment by danda1man** [comment]
Makes sense, well to make things consistent and build properly, the map and min files should also get marked as not readonly.  The checkout issue doesn't break builds, just an annoyance.

**Comment by madskristensen** [comment]
Yeah. I'll try to ask around if there is a way to do it

**Comment by madskristensen** [comment]
I just talked to one of the Visual Studio developers and he says that there is no way to check files out from TFS from MSbuild. He says that you should never modify a file that is part of the project, so he recommends that you don't include the compiled files in the project.

I'll have to close this issue.

**Comment by matthewpavkov** [comment]
I know this is a closed issue, but I have everything set up in TFS and tied to the build process and it checks out the files for me. @danda1man

**Comment by madskristensen** [comment]
I think it depends on what type of source control system you use and, in the case of TFS, what mode you're using.

**Comment by danda1man** [comment]
@matthewpavkov, we don't use TFS for CI builds, the main issue I was encountering in my workflow was keeping compile on build which would break since it tried to edit the file while it was read only.

@madskristensen, seems like a weird suggestion from the VS dev to not include the min/map file in the project.  If you used ASP.NET bundling/minification for everything, it would be ok.  But if you need min files on publish, you would have to create a custom publish action to get the min files into the publish (unless there is something I am missing there, but I tried a couple things and the compiled files never appear).  Can you still set the min and map files to not readonly in the MS Build task?

**Comment by madskristensen** [comment]
Yes, the `min` and `map` files will have the readonly flag removed by the MSBuild task

**Comment by madskristensen** [comment]
No, the `min` file did remove the readonly flag. I'm making that change now

**Comment by jerone** [comment]
It looks like this issue has appeared again. When *rebuild*ing my project I'm getting access denied issues on files. Removing the readonly flag on the folder solved the issue.

```log
Access to the path '..\js\file.js' is denied.
```

*****

_Microsoft Visual Studio Professional 2015 Version 14.0.24720.00 Update 1
Web Compiler   1.10.305
Windows 8.1 Pro
Project is on TFS_

**Comment by madskristensen** [comment]
@jerone Thanks for the heads up. This is now fixed
