### ISSUE TITLE
Add all less files in folder to compiler

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/WebCompiler#58]
Now i need to right click each .less file to add them to 'compilerconfig.json' would be nice if this would be a click like you can optimize all images in a folder. Something like 'compile all less files in folder'

![addallless](https://cloud.githubusercontent.com/assets/4510245/9005153/13dee754-377c-11e5-8bd1-191db6985016.png)

**Comment by markvantilburg** [comment]
Multi select also doesn't work in the solution explorer view if you select multiple files only the first gets compiled / re-compiled.

**Comment by madskristensen** [comment]
Would a dedicated shortcut for compiling all files do? I just committed code for that as per bug #61

**Comment by markvantilburg** [comment]
A recompile button would only help if there was a quick way to add the files to the compiler config.

**Comment by madskristensen** [comment]
Fixed with latest commits
