### ISSUE TITLE
Enable XXX on build not team dependant?

### ISSUE THREAD

**Issue by CheloXL** [madskristensen/WebCompiler#60]
As things are right now, it's quite complicated to setup a build system (at least for me) mostly because I have to replicate everything I have setup in my machine in every other developer machine.

When I enable the bundling/minifier to run on build, that setting now is replicated into every other developer machine. Since I'm the one that plays with css/js, that makes a lot of noise because they have to discard the changes to css/js they produce as part of their build process.

Previously (WE2013), unless they have installed the plugin, nothing were changed and I were in control of the files. Is there a way to not have this installed as a nuget package, but continue to be able to run the bundling/minification on build?

**Comment by madskristensen** [comment]
There is not, but it is a good idea

**Comment by madskristensen** [comment]
Would a dedicated shortcut for compiling all files do? I just committed code for that as per bug #61

**Comment by madskristensen** [comment]
The Shift+Alt+Y takes care of this and does so by avoiding the potential weird behavior of compiling only on VS build events which is not a guaranteed event
