### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by RaptorCZ** [madskristensen/WebCompiler#66]
I'm getting updates for WebCompiler almost every day. Is there any changelog? Maybe just simple txt file.

And based on changesets I found that WebCompiler is not using dotless anymore. Does it mean there is old NodeJS version back as in WE2013?

**Comment by madskristensen** [comment]
Yeah, there are lots of updates at the moment due to heavy feedback on missing features. I'm adding them as fast as I can. I'll start keeping a changelog on the VS Gallery description page.

Correct, it now uses node.js to execute the LESS compiler instead of dotless.

**Comment by RaptorCZ** [comment]
Ok, thnx for info. Now I can test and use this extension. DotLess doesn't work on our LESS files, so WebCompiler has been useless. Now it should work as before.

**Comment by madskristensen** [comment]
You can get the latest from here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/
