### ISSUE TITLE
Compile up the LESS @import chain

### ISSUE THREAD

**Issue by nokturnal** [madskristensen/WebCompiler#67]
I am having an issue which will probably be answered by way of this question and scenario...

Does this new extension maintain the same functionality as Web Essentials where it will compile files that contain an import to another file?  Meaning:

global.less

    @import 'foo.less';
    @import 'bar.less';
    
    #global-container {
        ......
    }
    ....

... and if you make a modification to foo.less or bar.less, will it automatically compile global.less?

**Comment by madskristensen** [comment]
Yes it will

**Comment by nokturnal** [comment]
If that is the case, then I am experiencing and issue :)  This is not happening... changes to "child" LESS files do not cause compilation of "parent" LESS files...

I am opening a project that was previously built with VS2013 and Web Essentials 2013... I have right clicked on the files in question and selected "compile" which created the compilation JSON file...

**Comment by madskristensen** [comment]
If the child file itself is also added as an `inputFile` in the `compilerconfig.json` file, then it won't trigger parent chain imports to recompile

**Comment by nokturnal** [comment]
AHHHHHHHHHHHHHHHH... that makes sense :)  I hope this helps someone else.  Thanks for the wicked work @madskristensen

**Comment by madskristensen** [comment]
I can repro this issue and a fix is coming today
