### ISSUE TITLE
Need a way to specify global options in a project

### ISSUE THREAD

**Issue by BrandonLive** [madskristensen/WebCompiler#69]
This is particularly necessary in the current state without globbing support.

Basically, I shouldn't have to specify "strictMath" for each and every LESS file in my project, but should be able to specify it once for all of them.
(if there is a way to do this that I somehow missed, please add it to the readme!)

**Comment by madskristensen** [comment]
That's a good idea

**Comment by scott-xu** [comment]
:+1:

**Comment by LordJZ** [comment]
For parity with Web Essentials 2013, it should be possible to specify to allow all files to be compiled and have some default options, per-project or global for all projects.

**Comment by madskristensen** [comment]
Can you please test it out in the latest build: http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

`Next time a file is added to compilerconfig.json through the context-menu, a compilerconfig.json.defaults is created`

**Comment by titobf** [comment]
Hi Mad, is it possible to disable minification of LESS files globally? Because I'm specifying this for every LESS entry:

"minify": {
                "enabled": false
            }

and maybe there's already a better way of doing it.

Thanks!

**Comment by madskristensen** [comment]
You can't specify default minification settings yet, like you can for the compiler settings. It's coming though

**Comment by kipusoep** [comment]
+1 for global setting which can be synced between developers/projects :-)

**Comment by gentoo90** [comment]
What about a global solution settings file? If there are multiple web-projects in a solutions, this would be more convenient.

**Comment by aukgit** [comment]
+1, it was already there in the previous Web Essential using webessential json config.
