### ISSUE TITLE
Can add the same file more than once

### ISSUE THREAD

**Issue by scottdorman** [madskristensen/WebCompiler#7]
Right clicking on a .less file and selecting "Compile file..." will add it to the `compilerconfig.json` file. Repeating that process allows me to compile the file again, which results in a second entry in the `compilerconfig.json` file. It seems like I should only be able to add the file once.

**Comment by madskristensen** [comment]
Good idea. Should the right-click button say "Re-compile file" instead then?

**Comment by scottdorman** [comment]
It could. The file is automatically recompiled when it's saved, but (at least in my case) that means I have to keep my main .less file open and resave it any time one of the imported files is changed. Having a "recompile" menu option would allow me to just right-click on the file and recompile it. (An awesome solution would be for the compiler to "read" the imports and setup a file watcher on each of the imported files - then if any of the imported files changes, the main file gets recompiled automatically.)

Having a "Stop compiling" menu option which removes the entry from `compilerconfig.json` would be convenient as well. (I know I can just manually remove it, but the menu option would be nice for completeness.)
