### ISSUE TITLE
Minified .js encoded to UTF8 and replacing åäö with �

### ISSUE THREAD

**Issue by regularroutine** [madskristensen/WebCompiler#71]
How can I change this behaviour or fix the issue?

**Comment by madskristensen** [comment]
What are you compiling? LESS, Sass, CoffeeScript?

**Comment by regularroutine** [comment]
Javascript, it might have been where the file came from (unsure). The unmidified worked fine. 
I opened it and saved back as UTF8 and recompiled. The min file is now correct.

**Comment by madskristensen** [comment]
So you're compiling CoffeeScript to JS and when this extension creates the .min.js file it causes the issue in the .min.js file only?

**Comment by regularroutine** [comment]
I think this issue was related to VS.
