### ISSUE TITLE
Compile on build runs too late

### ISSUE THREAD

**Issue by xilefius** [madskristensen/WebCompiler#73]
I installed the "Compile on build" nuget package, and removed the compiled .css file from source control.

But when i run my Azure deploy build it cannot find the .css file. It seems the WebCompiler runs after the deploy tries to create the publish file, resulting in missing files because the WebCompiler did not run yet.

I could fix this by changing the target in the "BuildWebCompiler.targets" file from

Target Name="WebCompile" AfterTargets="Build"
to
Target Name="WebCompile" AfterTargets="Compile"

resulting in running WebCompiler after the main compile step and before other "after build" steps.

Could you please change the BuildWebCompiler.targets file to run after the Compile instead of Build step? Thanks in advance

**Comment by madskristensen** [comment]
Yes, that's a great idea. I'll do that
