### ISSUE TITLE
Could not compile FontAwesome v4.3.0 LESS files

### ISSUE THREAD

**Issue by brakmic** [madskristensen/WebCompiler#76]
Hi,

Following your tweet on testing the latest version of WebCompile I thought it would be at best if I just use a well known library like FontAwesome and try to compile some of its files.

I've tried to compile *core.less* and *animated.less* but all I get is an error regarding the *@fa-css-prefix* variable.

Regards, 
Harris

![less_compile](https://cloud.githubusercontent.com/assets/56779/9236416/0fc786bc-4145-11e5-8e44-199e4d9328f2.png)

**Comment by brakmic** [comment]
There are also a few warnings. Non-related have been filtered out.

![warning](https://cloud.githubusercontent.com/assets/56779/9236614/2b72487e-4146-11e5-9303-a66e676e925a.png)

**Comment by madskristensen** [comment]
Thanks for testing. I'll take a look

**Comment by madskristensen** [comment]
Ok, I've done some investigation.

Just like Bootstrap does it, FontAwesome also imports all the files into a single of the .LESS files and that's the one that will be compiled. I just verified that compiling `font-awesome.less` works just fine.
