### ISSUE TITLE
v1.2.126 can't build project

### ISSUE THREAD

**Issue by RonPeters** [madskristensen/WebCompiler#77]
After upgrading from 1.1 to 1.2, I can no longer build my project. The targets file references a tool that is not in the tools directory. Downgrading to v1.1.117 resolves the issue.

The "WebCompiler.CompilerBuildTask" task could not be loaded from the assembly [...mypath...]\packages\BuildWebCompiler.1.2.126\build\..\tools\WebCompiler.exe. Could not load file or assembly 'file:///[...mypath...]\packages\BuildWebCompiler.1.2.126\tools\WebCompiler.exe' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by madskristensen** [comment]
This has now been fixed in the latest nightly 1.2.127 and higher. Thanks for reporting this
