### ISSUE TITLE
Does not compile .less file on save when running website

### ISSUE THREAD

**Issue by jlkalberer** [madskristensen/WebCompiler#79]
Hi,

I was working with a MVC4 site this weekend and I was modifying the .less files while the site was running.

In order to update the CSS I would have to manually trigger the compile via right click or the keyboard shortcut.

I'm not sure if this is by design or I was experiencing a bug.

Thanks

**Comment by madskristensen** [comment]
Does this only reproduce when VS was running the app/site (debugger attached)?

**Comment by jlkalberer** [comment]
That's when I was seeing it and I restarted VS a few times.  

I won't have the machine to test again until this weekend.

**Comment by madskristensen** [comment]
There is no logic in Web Compiler to differentiate between a running and non-running website. It should work all the same

**Comment by jlkalberer** [comment]
I was working on the laptop again and could not reproduce the issue.  I'm not sure what was going on.
