### ISSUE TITLE
Image paths in LESS files incorrect 

### ISSUE THREAD

**Issue by terzano** [madskristensen/WebCompiler#81]
Under version 1.2.127 relative paths in LESS files are not being converted to their relative counterpart based on the output file location. It looks like they are left untouched.

**Comment by madskristensen** [comment]
You should set the option on the file in the `compilerconfig.json` file. It is fully supported

**Comment by terzano** [comment]
Thank you Mads for the quick response. Sorry, I didn't see it on the docs. 
It used to be the default behavior in VS2013. I appreciate all your hard work and dedication.

**Comment by 33Leezer33** [comment]
Hi there! I am right that there is no docs about the Settings for the compilerconfig.json on Mads, GitHub, or where can i find it? I got the same issue as terzano; thats with the relative paths....
Thanks for any hint!
greetings

**Comment by madskristensen** [comment]
It's in intellisense inside the compilerconfig.json file only. I should turn relative path conversion on by default

**Comment by 33Leezer33** [comment]
Thanks for your reply, it worked with this option!
