### ISSUE TITLE
Issue with relative paths in compilerconfig.json

### ISSUE THREAD

**Issue by 33Leezer33** [madskristensen/WebCompiler#82]
Hi there! I am right that there is no docs about the Settings for the compilerconfig.json on Mads, GitHub, or where can i find it? I got the same issue as terzano; that with the relative paths....
 so its that ive on the css file following output generated:

in the repository
 1. background-image: url("../../resources/images/customerAbba/img1.png")
 on the working copy its wrongly outputted
 2. background-Image: URL("../Images/customerAbba/img1.png")

Thanks for any hint!
 greetings
P.S. im new to github, hope i acted right with my issue..

**Comment by madskristensen** [comment]
Is this for Sass or LESS files?

**Comment by madskristensen** [comment]
Fixed in latest commit. You might want to consider using root relative paths instead.
