### ISSUE TITLE
Adding LESS files to compilation error on build

### ISSUE THREAD

**Issue by RonPeters** [madskristensen/WebCompiler#83]
Running v1.2.133. Right click and compile a LESS file works fine. If I add LESS files to compilation, I get the following error (1 error per file referenced):

'node' is not recognized as an internal or external command,
operable program or batch file.

Workaround: remove LESS files from compilation and compile manually

**Comment by madskristensen** [comment]
I can not reproduce this issue. I just tried with the latest build found here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

I right-clicked on `compilerconfig.json` and selected `Enable compile on build...`. Then when I build my project it correctly runs the compiler. However, if you have errors in `compilerconfig.json` then it won't work. You have to make sure that you have at least the same version of the NuGet package that `Enable compile on build..` installs as the version of the extension. 

Try to update your NuGet package, either manually using `Manage NuGet Packages...` or by disable  compile on build and then enable it again

**Comment by RonPeters** [comment]
I had updated the Nuget packages but that did not help. The vsix extension is set to automatically update.

Disabling compile on build and enabling it again worked. It must have forced the new extension to get registered. Thanks.
