### ISSUE TITLE
Hide compiled files under main file e.g. hide *.js under *.coffee files

### ISSUE THREAD

**Issue by stanislavromanov** [madskristensen/WebCompiler#86]
Currently in solution explorer you can see them both side by side (fig. 1), in Web Essentials 2013 you didn't see the compiled files, instead they were hidden under the main file thus reducing the clutter.

Can we make so this extension also hides compiled files under the main file? (fig. 2)

![](http://i.imgur.com/i99xrm4.jpg)

**Comment by madskristensen** [comment]
What project type are you seeing this behavior in? ASP.NET 5, WebForms, Website Project, or...?

**Comment by madskristensen** [comment]
@stanislavromanov can you please answer the question?

**Comment by stanislavromanov** [comment]
Hello,

It's just a standard node.js application. Here's a screenshot.

![](https://i.imgur.com/vRyyVaN.png)


- Why is it that `*.js` file is not under `*.coffee` file?
- Why is he creating `*.min.js` files for every file? Can I disable it globally?

**Comment by madskristensen** [comment]
I believe that is a limitation of the project system. C#, ASP.NET and Website projects all have the capability of file nesting programmatically, but not the JS type. I think it relies on pre-defined naming conventions. If you rename your .js file to app.coffee.js does it then nest automatically?

**Comment by madskristensen** [comment]
@stanislavromanov Any update?

**Comment by stanislavromanov** [comment]
@madskristensen 

Hello, no, `app.js.coffee` doesn't work as well.

![](https://i.imgur.com/Mui91Nl.jpg)

**Comment by madskristensen** [comment]
Ok, that's a limit on the project system then. An extension cannot add nesting if the project system doesn't support it. Looks like the node.js project has hardcoded some patterns for nesting so that the .min.js file will nest under the .js file, but that's about it. 

Perhaps @mousetraps can shed some light on this?

**Comment by madskristensen** [comment]
Closing due to no answer
