### ISSUE TITLE
support for --relative-urls

### ISSUE THREAD

**Issue by wolfpackt99** [madskristensen/WebCompiler#87]
I have a ton of nested less files that i now compile into one less file via imports.  Used to work fine with web essentials 2013.  Now that we've upgraded the result isn't acheiving what we need.  If i run the lessc --relative-urls some.less some.css the image paths in urls are replaced as desired.  Please advise.  is there a way in the compilerconfig.json to specify an optional argument for this.

**Comment by madskristensen** [comment]
Yes there is. In

**Comment by madskristensen** [comment]
Yes there is. In `compilerconfig.json` you can add an `options` object inside the object describing your current LESS file. Inside the newly created `options` element you can set the relative urls flag. The easiest way is actually to remove the file from compilation by removing it from `compilerconfig.json` and then adding it back by right-clicking the .less file and select "Compile file...".

**Comment by wolfpackt99** [comment]
I actually just figured this out by looking in code and see arguments. Then noticed the miniy option on the vs examples. I did not see it add it by default. Will try and see. Thanks for your prompt reply.
