### ISSUE TITLE
lessc.cmd not found

### ISSUE THREAD

**Issue by iMarti** [madskristensen/WebCompiler#88]
When compiling a LESS file, lessc.cmd is missing. That folder exists but is empty.

I tried to uninstall the WebCompiler extension and install it again.
I disabled then enabled the "Enable Compile on Build..." option, saw that the BuildWebCompiler v1.2.127 NuGet package was successfully installed, but the LESS compiler is still missing.

    "C:\Users\IM\AppData\Local\Temp\WebCompiler1.2.127\node_modules\.bin\lessc.cmd"' is not recognized as an internal or external command, operable program or batch file.

**Comment by iMarti** [comment]
I updated the BuildWebCompiler manually in the Package Manager Console and got the v1.3.135.

When compiling a less file I have the same error above, calling v1.2.127 even after restarting VS.

**Comment by madskristensen** [comment]
If you delete the `WebCompiler1.2.xxx` temp folder, will it be recreated correctly for you the first time you compile a file?

**Comment by iMarti** [comment]
Yes, it worked. It installed the lastest 1.3.136 version and compiled the file. Thanks.
