### ISSUE TITLE
Poor performance of Solution Explorer with WebCompiler/BundlerMinifier

### ISSUE THREAD

**Issue by nazar-kuzo** [madskristensen/WebCompiler#89]
These two nugget packages makes Visual Studio not responding when do some operations with file like rename,add,delete.

This hangs can be noticed when we have a plenty of objects in compilerconfig.json (in my case - 12) or  in bundleconfig.json (in my case - 6).

I assume that defined tasks in .tagret file a triggered by performing some actions with files web project and takes some time to finish.

Please, write me back if you need detailed description.

**Comment by nazar-kuzo** [comment]
Possible fix:

change AfterTarges from "Compile" to "Build" in .target file of WebCompiler/BundlerMinifier extensions or nuget packages

links to .target files

AppData\Local\Microsoft\VisualStudio\14.0\Extensions\{autogenerated}\MSBuild\BuildWebCompiler.targets
AppData\Local\Microsoft\VisualStudio\14.0\Extensions\{autogenerated}\MSBuild\BuildBundlerMinifier.targets
{SolutionDir}\packages\BuildBundlerMinifier{Version}\build\BuildBundlerMinifier.targets
{SolutionDir}\packages\BuildWebCompiler{Version}\build\BuildWebCompiler.targets

**Comment by madskristensen** [comment]
Please let me know if this fixes the issue. If so, I'll make the change back to "Build" in the NuGet package

**Comment by nazar-kuzo** [comment]
Yes, It fixes this issue.

**Comment by madskristensen** [comment]
Thanks for testing it. I'll change it from "Compile" to "Build" so that the next version will do the right thing

**Comment by scott-xu** [comment]
It will reopen https://github.com/madskristensen/WebCompiler/issues/73
