### ISSUE TITLE
comment crashes web compiler

### ISSUE THREAD

**Issue by mkonstan** [madskristensen/WebCompiler#93]
Hi,

I am on the Web Compiler version 1.3.139 and it looks like it no longer plays nicely with comments in .scss file. For example sample.scss (see below) results in practically blank css output.

Thank you,
Max

![image](https://cloud.githubusercontent.com/assets/2441464/9590219/48098a00-5001-11e5-90f9-9fd9e6df8ee5.png)

**Comment by madskristensen** [comment]
Fixed in 1.3.140

**Comment by mkonstan** [comment]
Yes. I just installed your 1.3.140 build from the link in the other post and it fixed this issue for me.
Thank you.

**Comment by madskristensen** [comment]
Great. Sorry for the inconvenience and thanks for opening the issue
