### ISSUE TITLE
Problems to create SourceMap-File for SCSS

### ISSUE THREAD

**Issue by kojote79** [madskristensen/WebCompiler#95]
Hi,
in the previous version (1.2.xxx) when I set the "sourceMap"-Parameter in the config-File, the map file of a .scss-document was created correctly.
Now, after an update on 1.3.140 the map-file is no longer created.

here is my config-file:
[
  {
    "outputFile": "Content/Css/site.css",
    "inputFile": "Content/Css/site.scss",
    "minify": {
        "enabled": true
    },
    "includeInProject": true,
    "sourceMap": true,
    "options":{}
  }
]

Info: I work with Visual Studio Community 2015

Thank you for checking

**Comment by madskristensen** [comment]
The source map is embedded into the .css file using a DataURI. Do you see it?

**Comment by kojote79** [comment]
Hi, 
Thanks for the explanation - i can see it and it works fine.

Thank you an greetings
