### ISSUE TITLE
TypeError: require is not a function

### ISSUE THREAD

**Issue by cliche7** [madskristensen/WebCompiler#98]
```
TypeError: require is not a function
```

I got this error message when running my web app. It points to this line in one of the compiled js:

```
iced = require('iced-runtime');
```

How can I get around this issue?

edit: grammar

**Comment by madskristensen** [comment]
Try deleting the temp folder located at %localappdata%\Temp\WebCompiler[version] and then open VS again

**Comment by madskristensen** [comment]
I've made recovery of that folder automatic. Can you please install the latest CI build from here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/ and let me know if that fixed the issue?

**Comment by cliche7** [comment]
I've installed ```1.3.147``` and It still doesn't work unfortunately. Are you supposed to run that line of code in the web browser? Or is there a library that I should include to be able to run ```require()```?

**Comment by atifaziz** [comment]
I'm using 1.8.270 and still running into this issue. However, since I am using RequireJS in my project (but not using or loading iced-runtime), I get a slightly different error:

> Uncaught Error: Module name "iced-runtime" has not been loaded yet for context: _. Use require([])
> http://requirejs.org/docs/errors.html#notloaded

Is there anyway to disable *iced* support at a project-level?
