### ISSUE TITLE
Compile all compilerConfig.json files in solution on "Re-compile all files…"

### ISSUE THREAD

**Issue by casperno** [madskristensen/WebCompiler#99]
Multiple compilerconfig.json files in various folders is supported, but they're not  read on "Re-compile all files…".

Right now a compilerconfig.json can be placed in a folder and can be compiled when right clicked, but "Re-compile all files…" won't read it. I'd like "Re-compile all files…" to do a compile with all compilerconfig.json in the project.

We use externals so one compilerconfig.json on root is a bit cumbersome to handle. 

Please?

**Comment by madskristensen** [comment]
I didn't restrict the use of multiple `compilerconfig.json` files, but it was always meant to just be a single file in the root of the project. It seems like a logical thing to support in **Re-compile all files...** though

**Comment by casperno** [comment]
Eagerly awaiting enhancement.
